### ISSUE TITLE
MCF threads or POSIX threads ?

### ISSUE THREAD

**Issue by sisyphus** [StrawberryPerl/Perl-Dist-Strawberry#104]
When Brecht Sanders provided his early builds of gcc-13, their threading model was mcf threads.
He also publicly stated that he did not wish to provide posix threads versions of gcc-13. 

In a subsequent statement, he said that there are some issues with mcf threads - but I don't know what they are.
Anyway, I suspect that's why the winlibs website now offers  both posix and mcf builds of gcc-13.1.0 (release 5).
(Apparently the issues with the mcf compilers aren't so serious as to make them unfit for release.)

Any thoughts on which to use ?
Has Strawberry Perl decided on which one to use for their impending perl releases ?

I gather that the general view amongst the vendors of mingw-w64 compilers is to discontinue the "posix threads" builds in favour of "mcf threads" builds, though the configure option to build for "posix threads" will (I presume) remain.
That seems to me to be a good reason to start using the mcf versions.
OTOH, the use of the posix threads compilers goes back a long way - so maybe it's better to just stick with "the devil you know".

Cheers,
Rob

**Comment by shawnlaffan** [comment]
At this stage it's the devil one knows.  I'd rather not shake out any more arthropods before the release.  

FWIW, I've just run a build using winlibs gcc-13.1 release 5 with posix threads (c.f. https://github.com/StrawberryPerl/spbuild/issues/17).  It's all consistent with previous runs (the usual known failures) but compilation is much faster.  

I'll upload a new dev release soonish.  Hopefully that will be the last, or nearly so.

**Comment by shawnlaffan** [comment]
extlibs are at https://github.com/StrawberryPerl/build-extlibs/releases/tag/dev_gcc13.1_20230606 (although libgd needs to be rebuilt and probably dropped back to 2.3.2).

**Comment by sisyphus** [comment]
> At this stage it's the devil one knows.

Fair enough.
I'll use the winlibs MCF variant for my own builds ... just to be different.
Closing.

Cheers,
Rob

**Comment by shawnlaffan** [comment]
> I'll use the winlibs MCF variant for my own builds ... just to be different.

We might yet release an MCF variant, but some time after we get 5.36 and 5.38 out the door.  Naturally we'll lean on your experiences...
