### ISSUE TITLE
5.38.1 release?

### ISSUE THREAD

**Issue by rwp0** [StrawberryPerl/Perl-Dist-Strawberry#106]
Thanks for the release today 🙏🏻 but:

https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_5380RC1_20230618_gcc13

Why the release is titled 5.38.1 and not 5.38.0? 🤔

![Screenshot_20230618_133013_GitHub.jpg](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/assets/68062695/93ef57c9-2349-4705-93cf-a2ce38500181)

**Comment by shawnlaffan** [comment]
A copy paste error.  Fixed now.  

Thanks for reporting.
