### ISSUE TITLE
[SP-5.38.0.1] $Config{libpth} contains non-existent directory

### ISSUE THREAD

**Issue by sisyphus** [StrawberryPerl/Perl-Dist-Strawberry#107]
<code>
D:\>perl -V:libpth
libpth='C:\sp\_64\sp-5.38.0-RC1\strawberry\c\lib C:\sp\_64\sp-5.38.0-RC1\strawberry\c\x86_64-w64-mingw32\lib C:\sp\_64\sp-5.38.0-RC1\strawberry\c\lib\gcc\x86_64-w64-mingw32\8.3.0';
</code>

It's the final directory (<code>C:\sp\_64\sp-5.38.0-RC1\strawberry\c\lib\gcc\x86_64-w64-mingw32\8.3.0</code>) that doesn't exist.
"8.3.0" needs to be changed to "13.1.0".

However, I don't think this is of much consequence.
AFAIK, with gcc-8.3.0, that particular location was specified because that's where libquadmath.dll.a and libgfortran.dll.a resided - but they've now been moved elsewhere.
I think it's likely that this particular directory could now be removed from <code>libpth</code>, though that's probably only necessary if you want to avoid having people wonder why it's specified.

One other thing I noticed in unzipping 5.38.0-RC1 is that everything got unpacked into a directory named "strawberry".
Again, this is of little (if any) importance ... but it's something I hadn't seen with a "portable" zip before, so I just thought I'd mention it.

@shawnlaffan, @genio, I'll leave this issue to you guys to close, at your convenience.

Cheers,
Rob

**Comment by shawnlaffan** [comment]
Thanks Rob.  

I suspect the gcc-8.3.0 line is coming from the libmysql package as we are re-using it from the 5.32 builds.  If anyone has a suggestion for how to clean it out automatically than that would be appreciated.  

I'll look into the subfolder.  The zip file is the generated build archive but perhaps something has gone awry.  I've had the restorepoints option set for these builds and perhaps it, or a related setting, is interfering with the archiving process.

**Comment by shawnlaffan** [comment]
WRT the directory, my guess is a File::Find::Rule issue.  

https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/63b69fb44c66a1b645d1c103e85d98647597459f/lib/Perl/Dist/Strawberry.pm#LL492C11-L492C11

The 5.38 build was done using the latest 5.36 dev release, where the 5.36 dev releases used 5.32.  We have patched File::Find::Rule for 5.36 and might need to do more.

**Comment by shawnlaffan** [comment]
The GCC version is probably from here: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/63b69fb44c66a1b645d1c103e85d98647597459f/share/64bit-5.38.0.1.pp#L434

It also affects the 5.36 builds.

**Comment by shawnlaffan** [comment]
Both issues should be fixed now.  I'll close this once I have another dev release out.

**Comment by shawnlaffan** [comment]
Perl 5.58.0 RC2 dev release is at https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_5.38.0_RC2_20230626_gcc13
