### ISSUE TITLE
Duplication of "-D__USE_MINGW_ANSI_STDIO" in CCFLAGS in 5.38.0_20230705

### ISSUE THREAD

**Issue by sisyphus** [StrawberryPerl/Perl-Dist-Strawberry#113]
This probably applies to the msi and pdl distros, too, but I've looked only at the portable distro.
The duplication has likely been there all along, and I've only just now noticed it.
Back when 5.32.1 was built you had to take steps to include the flag - but the current GNUmakefile inserts it automatically, unless one takes steps to have it omitted.

Anyway, just something you could tidy up when you get around to it ... or not ;-)

Cheers,
Rob

**Comment by shawnlaffan** [comment]
It's added in the build config so will also be present in the PDL and MSI builds.  
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/d95320e27c0a9a21cffb04353a42b0295027b395/share/64bit-5.38.0.1.pp#L58

It's easy enough to comment out.  

Which version of Perl was it added to GNUmakefile?

**Comment by shawnlaffan** [comment]
To answer my own question, it was in 5.33.6.
https://github.com/Perl/perl5/commit/b14ae3c3b36461b9e396451434fba1dff9a69bb8
