### ISSUE TITLE
Question, not issue - how long before 5.38 hits https://strawberryperl.com/?

### ISSUE THREAD

**Issue by matthewpersico** [StrawberryPerl/Perl-Dist-Strawberry#114]
TPRC is next week in Toronto. Would be great to make an announcement there.

**Comment by genio** [comment]
https://www.nntp.perl.org/group/perl.perl5.porters/2023/07/msg266628.html

As for updating the strawberryperl.com site, that will happen as soon as we can resolve the server access issues.

**Comment by genio** [comment]
@adamkennedy Can you help us out on that front?

**Comment by shawnlaffan** [comment]
FWIW, I have prepared a draft release with the most recent builds of 5.36.1 and 5.38.0 (yesterday, AEST).  Until it is released it will be visible only to people with push access to the repo.  Comments on the release text welcome, as is the green light to release it.  

Note that this does not include the HTML template files that are used for each release on the main web site.  They need editing to note main changes and thus are best shared a different way.  

We should probably merge PR #115 onto the master branch before releasing (although there's a lot to review).

**Comment by shawnlaffan** [comment]
TPRF is imminent.  I'll open up the latest release so users can be directed to it.  

This will be final 5.36.1.1 and 5.38.0.1.  Further changes can be released with higher version numbers (e.g. 5.38.0.2).

**Comment by wchristian** [comment]
i've added some info and pinged adam's email here: https://www.nntp.perl.org/group/perl.perl5.porters/2023/07/msg266666.html

**Comment by zmughal** [comment]
Once the website is updated, the [Chocolatey package](https://community.chocolatey.org/packages/strawberryperl) should get updated (automatically, I believe) at <https://github.com/Thilas/chocolatey-packages/tree/master/strawberryperl>.

**Comment by shawnlaffan** [comment]
> from @shadowcat-mst:
> 
> > mst> haarg, genio, Mithaldu: need to chase adam up again, am in contact and should be able to get control of it soonish

Do we have an update on this?

**Comment by wchristian** [comment]
i pinged @shadowcat-mst

**Comment by shadowcat-mst** [comment]
@shawnlaffan

    < mst> CONTACT
     * mst casts 'summon genio'
    < ether> ?
    < mst> $ pwd
    < mst> /home/strawberry
    < mst> ether: [hacker voice] I'm in.

Access achieved, just need to co-ordinate with @genio to make sure the right things go in the right places.

(this sort of infrastructure stuff tends to get discussed on #toolchain on irc.perl.org if anybody wants to hang out there and get faster updates and/or join the relevant conversations)

**Comment by shawnlaffan** [comment]
Thanks @shadowcat-mst - that's great news.  

Now we have the keys it is hopefully a quick process to get the site updated.

**Comment by shadowcat-mst** [comment]
got @genio in, somebody should report back as further progress gets made

**Comment by shadowcat-mst** [comment]
@shawnlaffan "work out where he's working -> work out who I know who also works there -> get them to harass him mercilessly until he talks to me -> harass him mercilessly myself until I get ssh access" is ... a process.

Sorry it took so long, I could moan about other people but I've kept getting distracted too so everybody feel free to just blame me for simplicity :D

**Comment by shawnlaffan** [comment]
@genio++ has now updated the website so this can be closed.
