### ISSUE TITLE
PPM up to 11.11_03 is incompatible with Win32 0.53

### ISSUE THREAD

**Issue by h-vn** [StrawberryPerl/Perl-Dist-Strawberry#12]
Win32::::IsWinNT() started checking its usage with version 0.53.

https://github.com/perl-libwin32/win32/blob/7746dcd8d9f290ce9ebe5b0609ac0b4b8e10b2d8/Win32.xs#L1312-L1319

This causes problems with PPM shipped with Strawberry Perl 5.30.1.1. One example is one reported by this RT issue:
https://rt.cpan.org/Public/Bug/Display.html?id=130354

PPM.pm line 227, the line where the problem actually is, currently does this:
   `!&Win32::IsWinNT && exists $Win9x_denied{lc($package)}) {`

Now it seems that because IsWinNT is called with ampersand, @_ is implicitly passed as arguments triggering the usage check added in Win32 0.53.

Changing line 227 in PPM.pm to this allows PPM to work as it did before:
   `!Win32::IsWinNT() && exists $Win9x_denied{lc($package)}) {`

There's also another similar call in PPM.pm seems to be for updates/upgrades only because it's not triggering problems with ppm installs.

**Comment by kmx** [comment]
fixed in 5.30.2.1
