### ISSUE TITLE
Malware Detection upon install of strawberry 5.38.0.1 portable

### ISSUE THREAD

**Issue by eZarg** [StrawberryPerl/Perl-Dist-Strawberry#123]
I tried the automated installer through berrybrew. It seemed to load everything ok. Then I scanned the strawberry download with Webroot Endpoint Protection CE23.3. It thinks GUITest.xs.dll is malware W32.Malware.Gen.
  OSname=MWin32; Osvers=10.0.17763.4499; archname=MSWin32-x64-multi-thread. (Windows 10 Pro.)
 uname Win32 strawberry-perl 5.38.0.1 # 12:34:49 Thu July 06 2023 x64. It said portable while going through the process.
eZarg

**Comment by shawnlaffan** [comment]
This is probably a false positive from your antivirus software.  I've had similar issues in the past with PAR::Packer and its component files, albeit with a different antivirus scanner.  

Are you able to report files to Webroot to check?  

Also, do you have the same issues with strawberry perl 5.32?

**Comment by sisyphus** [comment]
I usually upload files that are reported as malware to https://www.virustotal.com/gui/home/upload, from where they will be scanned by many antivirus  programs.
You will probably find that the vast majority (if not all) of those programs (apart from webroot of course) will state that GUITest.xs.dll is clean.

If they all claim that GUITest.xs.dll contains malware, then that probably warrants further investigation.

Cheers,
Rob

**Comment by eZarg** [comment]
I downloaded 5.38.01-64bit-PDL today, partly so I can practice the berrybrew switching, partly so I could test with WebRoot again, figuring if it was a wrong detection before, they would have fixed it by now. No detection this time. So presumably it was a false positive, as was suspected./ My last loaded Strawberry Perl was way before 5.32, so we can't compare those 2.
Thanks for everyone's efforts and patience.
eZarg

**Comment by shawnlaffan** [comment]
Good to hear this is resolved.  Thanks for the report and I'll close this issue now.
