### ISSUE TITLE
libwebp missing in 5.36 and 5.38

### ISSUE THREAD

**Issue by dk** [StrawberryPerl/Perl-Dist-Strawberry#125]
First of all, thank you all for picking up the project and making new releases - these were missed badly! 

I asked previously kmx to include libwebp into SP distro, as my project depends on these, and until 5.32 it had libwebp, libwebpdemux, and libwebpmux libraries. Would it be possible to add these to 5.38 as well? 

I would gladly submit a patch but I can't figure out what's needed for this - share/64bit-5.38.0.1.pp  points to the URLs that are also part of the build, so I guess something like this is needed but is not enough:

```
diff --git a/share/64bit-5.38.0.1.pp b/share/64bit-5.38.0.1.pp
index 45ae657..22bdabf 100644
--- a/share/64bit-5.38.0.1.pp
+++ b/share/64bit-5.38.0.1.pp
@@ -31,6 +31,7 @@
             mpc  => 'https://github.com/StrawberryPerl/build-extlibs/releases/download/dev_gcc13.1_20230606/64bit_mpc-1.3.1-bin_20230606.zip',
             mpfr => 'https://github.com/StrawberryPerl/build-extlibs/releases/download/dev_gcc13.1_20230606/64bit_mpfr-4.2.0-bin_20230606.zip',
             libgd           => 'https://github.com/StrawberryPerl/build-extlibs/releases/download/dev_gcc13.1_20230502/64bit_libgd-2.3.2-bin_20230502.zip',
+            libwebp => 'https://github.com/StrawberryPerl/build-extlibs/releases/download/dev_gcc13.1_20230606/64bit_libwebp-1.1.0-bin_20200712.zip',
             zgdb => 'https://github.com/StrawberryPerl/build-extlibs/releases/download/dev_gcc13.1_20230606/64bit_gdb-13.1-bin_20230626.zip',
             termcap => 'https://github.com/StrawberryPerl/build-extlibs/releases/download/dev_gcc13.1_20230606/64bit_termcap-1.3.1-bin_20230606.zip',
         },
```

**Comment by shawnlaffan** [comment]
Thanks for the report.  It seems libwebp was overlooked in the builds.  

I've opened https://github.com/StrawberryPerl/build-extlibs/issues/52 to track it.

**Comment by shawnlaffan** [comment]
libwebp is in SP 5.38.2.2 and will be in SP 5.40 releases.  It is not in the latest SP 5.36 release but that is not much of an issue given download stats (and we might not build a newer 5.36).  

I'll close this issue but it can be re-opened if need be.
