### ISSUE TITLE
OpenSSL 1.1.1 EOL

### ISSUE THREAD

**Issue by fabian-lauer** [StrawberryPerl/Perl-Dist-Strawberry#132]
Hi,

currently facing a problem in one of our company projects that the IT sec team is complaining about OpenSSL version used in StrawberryPerl.

Based on this information: https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/ end of life is very close.

Is there any idea or planed software release to fix this problem?
e.g. change version to 3.x.x

Thx.
Fabian

**Comment by shawnlaffan** [comment]
Thanks for the report.  We can have a go at building OpenSSL3.  I won't have a chance until later this month, though.  

The MSYS2 project have patches available that can be adapted if needed: https://github.com/msys2/MSYS2-packages/tree/master/openssl

**Comment by shawnlaffan** [comment]
SP 5.40 will use OpenSSL 3.3.0.
https://github.com/StrawberryPerl/build-extlibs/releases/tag/gcc13.2_ucrt_posix

There is a 5.40-RC1 available at https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_5.40.0_RC1_UCRT

**Comment by shawnlaffan** [comment]
SP 5.40.0.1 has now been released.  

https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_54001_64bit_UCRT

I'll close this issue now.  If there are issues with OpenSSL 3 then they can be raised in new issues.
