### ISSUE TITLE
fribidi missing in new build

### ISSUE THREAD

**Issue by dk** [StrawberryPerl/Perl-Dist-Strawberry#134]
A very similar problem to #125, there used to be a fribidi library in the 5.32 SB distro, but it's not there anymore

**Comment by shawnlaffan** [comment]
Thanks for reporting.  

It's in the build-extlibs system so must have been dropped when setting up the final build.

Until a new build is released you can download a version from https://github.com/StrawberryPerl/build-extlibs/releases/tag/dev_gcc13.1_20230606

**Comment by shawnlaffan** [comment]
libfribidi is in the 5.38.2.2 release: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_53822_64bit

**Comment by shawnlaffan** [comment]
I'll close this issue now but please re-open if it is also needed in a 5.36 release.
