### ISSUE TITLE
5.38 fails to build Math::Pari (works with 5.32)

### ISSUE THREAD

**Issue by kenneth-olwing** [StrawberryPerl/Perl-Dist-Strawberry#136]
Basically, the Makefile.PL downloads a pari-2.3.5.tar.gz and then proceeds to patch some files with the 'patch' utility.

With the second patch (patches\diff_2.3.5_stderr_clobber) it goes into a loop with "patching file src/language/init.c".

After fiddling with the patch file (saving it with CRLF instead of just LF apparently makes a difference...), it proceeds, but the compilation/assembly fails with assembler errors:
```
c:\tmp\cchuRWNb.s: Assembler messages:
c:\tmp\cchuRWNb.s:1377: Error: incorrect register `%edx' used with `q' suffix
c:\tmp\cchuRWNb.s:1757: Error: incorrect register `%eax' used with `q' suffix
c:\tmp\cchuRWNb.s:1790: Error: incorrect register `%r10d' used with `q' suffix
```

While the first part appears to be rooted in the patch utility, I get the same version 2.7.5 in 5.38 and 5.32. So different behavior for unknown reason.

The second part, assuming the patching doesn't get entirely cocked up, looks more like the pari code & compiler/assembler problem so maybe it's not much that can be done on the Strawberry side...:-/...but perhaps someone more knowledgeable can make heads or tails of it all.

Personally, I'm not that affected by it I think, I just stumble on it when dragging in dependencies, some of which (like Crypt::Prime IIRC) requires Math::Pari. As noted in the subject, it installs fine with 5.32.

In any case, any insight interesting of course,

Thanks,
ken1

**Comment by sisyphus** [comment]
> In any case, any insight interesting of course,

I didn't have Math::Pari installed on either my SP-5.32.1 or my SP-5.38.0.

So I ran <code>cpan -i Math:Pari</code> on SP-5.32.1 and it ran fine ... as you said it would.

Given your warning about the problem with patch,exe on SP-5.38.0, I next replaced that patch.exe in SP-5.38.0 (version 2.7.5) with the patch.exe from SP-5.32.1 (version 2.5.9).

I then ran <code>cpan -i Math:Pari</code> on SP-5.38.0, and that also worked flawlessly.

If I switch back to patch-2.7.5 on SP-5.38.0, then I hit the looping error that you described.
But I think that this issue with patch.exe is the <b>*only*</b> issue that exists.

Using the good patch (2.5.9), the relevant section of the Math::Pari build begins with:
```
Looking for patches for 2.3.5...
Patching...
patching file utils/inc.h
... Apparently, your patch takes flag --binary...
cd pari-2.3.5 && patch -p1 --binary < ..\patches\diff_2.3.5_mingw-w64
patching file src\gp\highlvl.c
patching file src/language/es.c
cd pari-2.3.5 && patch -p1 --binary < ..\patches\diff_2.3.5_stderr_clobber
patching file src/language/init.c
cd pari-2.3.5 && patch -p1 --binary < ..\patches\diff_2.3.5_mingw_longlong
....
````
while the same section, using the crook patch (2.7.5) begins with:
```
Looking for patches for 2.3.5...
Patching...
patching file utils/inc.h
patch: **** Can't rename file utils/inc.h.ofdzcLt to utils/inc.h : No such file or directory
cd pari-2.3.5 && patch -p1  < ..\patches\diff_2.3.5_mingw-w64
patching file 'src\gp\highlvl.c'
patching file src/language/es.c
cd pari-2.3.5 && patch -p1  < ..\patches\diff_2.3.5_stderr_clobber
patching file src/language/init.c
patching file src/language/init.c
....

Cheers,
Rob

**Comment by kenneth-olwing** [comment]
Wooh! Yes.

It appears I've misdiagnosed which patch.exe I had available in 5.38 vs 5.32, I had a ton of windows seeing either of the versions  during experimenting and ran patch -v in two 5.38 windows instead of one in either, so I thought they had the same version (2.7.5).

So I concur, just switching in patch.exe makes the install work. Now I'll begin wiring it in to my full dependency build system (it doesn't help that I'm behind a firewall and have to provide the pari tarball via the "pari_tgz=xxx" mechanism...). I'll report back.

And for completeness, patch.exe appears to be statically linked with the exception of the standard windows dlls, so it should be safe to move around without hitting weird dll dependencies.

Thanks for the insight :-)

ken1

**Comment by shawnlaffan** [comment]
This could be related to https://github.com/StrawberryPerl/build-extlibs/issues/51 which I have yet to sort out. 

The patch that comes with 5.32 does not work with some of the patches in the build system (#74).  Ideally we will get these issues sorted, otherwise we can look for an alternate patch.exe.

**Comment by shawnlaffan** [comment]
Math::Pari builds and tests without error for me when using Strawberry Perl 5.38.2.1 (https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_53821_64bit).

That version ships with the same ```patch``` utility as 5.32 (as does [5.36.3.1](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_53631_64bit)).

**Comment by shawnlaffan** [comment]
I'll close this now.  If it is not fixed then I can re-open the issue.
