### ISSUE TITLE
Strawberry Perl Portable edition reports Perl's executable's path is tainted

### ISSUE THREAD

**Issue by jkeenan** [StrawberryPerl/Perl-Dist-Strawberry#14]
Please see https://rt.cpan.org/Ticket/Display.html?id=132264

```
#!/usr/bin/perl -wT
use strict;
use Scalar::Util qw(tainted);
use Config;

my $perl_path = $Config{perlpath};

if ($^O ne 'VMS') {
    $perl_path .= $Config{_exe}
        unless $perl_path =~ m/$Config{_exe}$/i;
}
(! tainted($perl_path) )
    ? print "Path to perl executable $perl_path is clean\n"
    : print "Path to perl executable $perl_path is tainted\n";
```

**Comment by kmx** [comment]
The whole `%Config` in portable strawberry perl is magic.

The first part is simple (just a little patch for original `Config.pm`): 
https://metacpan.org/release/Portable-Dist/source/lib/Portable/Dist.pm#L150

The main part is here:
https://metacpan.org/source/KMX/Portable-1.23/lib/Portable/Config.pm

**Comment by jkeenan** [comment]
> The whole `%Config` in portable strawberry perl is magic.
> 
> The first part is simple (just a little patch for original `Config.pm`):
> https://metacpan.org/release/Portable-Dist/source/lib/Portable/Dist.pm#L150
> 
> The main part is here:
> https://metacpan.org/source/KMX/Portable-1.23/lib/Portable/Config.pm

Thanks for investigating this.  Let me re-pose the question I asked in [the RT ticket cited above](https://rt.cpan.org/Ticket/Display.html?id=132264):

Is there any way to distinguish whether a given Strawberry Perl is "regular" or Portable?

Thank you very much.
Jim Keenan

**Comment by kmx** [comment]
There is no official way, just a hack (which is not guaranteed for the future) like:
```perl
my $is_portable = eval { require Config; defined $INC{'Portable.pm'} };
```
