### ISSUE TITLE
Add checksum files to releases

### ISSUE THREAD

**Issue by briandfoy** [StrawberryPerl/Perl-Dist-Strawberry#144]
Recently, someone asked about [checksums for the latest releases](https://www.reddit.com/r/perl/comments/175aig1/looking_for_checksums_for_strawberry_perl_binary/). Perhaps those files can be added to the GitHub release, since you'll need them for the strawberryperl.com listing too.

**Comment by genio** [comment]
Checksums are on the site and are in the releases.json file

**Comment by genio** [comment]
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_5380_5361
