### ISSUE TITLE
UCRT builds

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/Perl-Dist-Strawberry#152]
It's worth experimenting with UCRT.  

The relevant patch is https://github.com/Perl/perl5/commit/26b63da690b28dba2297996624585ef2813f8409

See also https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/150#issuecomment-1783953515

**Comment by sisyphus** [comment]
Another advantage of UCRT builds is that locales are then thread-safe - though that also requires at least 5.39.3 or 5.39.4 (IIRC),

Cheers,
Rob

**Comment by shawnlaffan** [comment]
SP 5.40 will use UCRT.  If all goes wll then we can consider a 5.38 UCRT build.

**Comment by shawnlaffan** [comment]
SP 5.40.0.1 uses UCRT.  
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_54001_64bit_UCRT

If we build a new 5.38 then it will likely also use UCRT (with appropriate patching).  That can be in its own issue, though, so I'll close this issue now.
