### ISSUE TITLE
libfribidi and libwebp

### ISSUE THREAD

**Issue by dk** [StrawberryPerl/Perl-Dist-Strawberry#16]
Dear all

Would you kindly consider adding libfribidi to the next Strawberry version? I'm hacking Prima GUI so that it can support advanced unicode stuff, right-to-left text input, and complex shaping, and fribidi plays a major role there.

Another, but less important addition, is the webp image format, that I included some time ago.  Would you possibly consider shipping libwebp, libwebpdemux, and libwebpmux? It's not critical and more of a nice-to-have, but if you do that I'd be very grateful.

/dk

**Comment by kmx** [comment]
Could you please try `libwebp` and `fribidi` from:
* http://strawberryperl.com/package/kmx/64_libs/gcc83-2020Q3/
* http://strawberryperl.com/package/kmx/32_libs/gcc83-2020Q3/

**Comment by dk** [comment]
Both work perfectly, thank you very much!
