### ISSUE TITLE
Error/problem installing Strawberry-Perl 5.38.0.1-64bit - Microsoft defender rejects the installation for unknown app

### ISSUE THREAD

**Issue by chalan51** [StrawberryPerl/Perl-Dist-Strawberry#164]
Hello,
I downloaded the .msi file to install Strawberry-Perl 5.38.0.1-64bit and Microsoft Defender rejects the process because the app is "unknown".
What is necessary to fix this issue?
Regards
Juan Manuel
![Strawberry Install error](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/assets/19984426/e7597877-59ef-4e13-b02f-41b8bd138c11)

**Comment by shawnlaffan** [comment]
This is appearing because the Strawberry Perl distributions are not signed.  If you go into the "more information" then there is usually an option to install it anyway.

**Comment by genio** [comment]
I'm going to close this out under the assumption that the work-around is ok for you.
