### ISSUE TITLE
remove dependency on WiX when MSI output is disabled

### ISSUE THREAD

**Issue by sergiotarxz** [StrawberryPerl/Perl-Dist-Strawberry#172]

**Comment by shawnlaffan** [comment]
This appears to be the relevant code:
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/427b95661366260b251015a2fb90fd2745aa0cbb/lib/Perl/Dist/Strawberry.pm#L87-L92

Adding a check for ```$ENV{SKIP_MSI_STEP}``` might be sufficient.  Maybe also check the list of steps for ```OutputMSI```.

**Comment by g-bougard** [comment]
Indeed, `candle.exe` & `light.exe` are required by `OutputMSI` and the related step will fail if run with not functional such binary.

But you can remove the related step from your `.pp` file and remove the `-wixbin_dir` option from the `bat` file so the step pointed out by @shawnlaffan will just be skipped.

**Comment by sergiotarxz** [comment]
@g-bougard That's what I am doing.

**Comment by sergiotarxz** [comment]
May I try to fix this issue? Can be cool to become a strawberry perl contributor.

**Comment by genio** [comment]
@sergiotarxz Of course. We're happy to get help from as many people as possible. If you want to discuss things with people, you can join the IRC channel as well.

**Comment by sergiotarxz** [comment]
@genio What irc channel?

**Comment by genio** [comment]
https://kiwiirc.com/nextclient/#irc://irc.perl.org/#win32?nick=mc-guest-?

**Comment by sergiotarxz** [comment]
I cannot connect to irc.perl.org it hangs forever...

**Comment by g-bougard** [comment]
> @g-bougard That's what I am doing.

Can you at least share the output showing your issue ? And maybe your script ?

**Comment by sergiotarxz** [comment]
I will share a reproducible example as soon as I can.

**Comment by shawnlaffan** [comment]
@sergiotarxz - have you been able to generate a reproducible example?

**Comment by sergiotarxz** [comment]
@shawnlaffan 
```
diff --git a/devel.utils/_build-5.39_local.bat b/devel.utils/_build-5.39_local.bat
index eb3a3f9..d7c020b 100644
--- a/devel.utils/_build-5.39_local.bat
+++ b/devel.utils/_build-5.39_local.bat
@@ -3,10 +3,8 @@
 
 ::set PERL_USE_UNSAFE_INC=1
 
-subst Z: C:\spbuild
-
-set SP=d:\berrybrew\5.32.1.1_64bit
-set PATH=%SP%\c\bin;%SP%\perl\bin;%SP%\perl\site\bin;Z:\sw\wix311;Z:\winlibs\bin;%PATH%
+set SP=C:\users\docker\desktop\straw
+set PATH=%SP%\c\bin;%SP%\perl\bin;%SP%\perl\site\bin;%PATH%
 set PERLEXE=%SP%\perl\bin\perl
 
 :: update blib - requires Build.PL to have been run
@@ -23,6 +21,6 @@ set TEST_JOBS=8
 
 ::set SKIP_MSI_STEP=1
 ::set SKIP_PDL_STEP=1
-%PERLEXE% -Mblib ..\script\perldist_strawberry -job ..\share\64bit-5.39.10.1.pp -test_core -beta=0 -interactive -restorepoints -wixbin_dir=z:\sw\wix311 -cpan_url https://cpan.metacpan.org
+%PERLEXE% -Mblib ..\script\perldist_strawberry -job ..\share\64bit-5.39.10.1.pp -test_core -beta=0 -interactive -restorepoints -cpan_url https://cpan.metacpan.org
 ```

**Comment by sergiotarxz** [comment]
@shawnlaffan You have to stop sending -wixbin_dir=z:\sw\wix311 in the build files and set the environment variable SKIP_MSI_STEP to a perl true value and the code will still need wixbin_dir or it will refuse to work even when wixbin is no longer needed.

**Comment by shawnlaffan** [comment]
Looking back over the thread, there is this comment: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/172#issuecomment-1977789601

So the change should just require an additional check for the env var:
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/2ba78fc83d0cc29d039b4987f85a92ff7febf376/lib/Perl/Dist/Strawberry.pm#L87
becomes
```perl
        if (defined $self->global->{wixbin_dir} && !$ENV{SKIP_MSI_STEP}) { 
```

@sergiotarxz - would you be up to implementing a PR?  It's not hard to do myself but it's good to have more contributors.

**Comment by shawnlaffan** [comment]
Actually it is slightly more complex than just a one-line change.  PR is in #194
