### ISSUE TITLE
virus detected in the cc1plus.exe file

### ISSUE THREAD

**Issue by icez3r0** [StrawberryPerl/Perl-Dist-Strawberry#176]
Currently I am using avast antivirus, and I did a check of the entire hard drive, when I jumped as a threat the file **cc1plus.exe** which is in the following file path (drive):\Strawberry\c\libexec\gcc\x86_64-w64-mingw32\13.1.0, I get the following message FileRepMalware, after that, I went to see the website called total virus, specify the file and I got more data, to this date https://www.virustotal.com/gui/file/ecde19e9a74b5cb580c5abd9873606f4539d288a08620f7103861cc9872e4d8e/detection

![Captura de pantalla_31-3-2024_41619_www virustotal com](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/assets/165555752/d46af0ea-310f-403c-bf72-85734beae271)
![Captura de pantalla_31-3-2024_4161_www virustotal com](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/assets/165555752/a9f72bb9-e6a9-44c9-8565-443c331d5f77)
![Captura de pantalla_31-3-2024_41528_www virustotal com](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/assets/165555752/036a21e9-31f4-40f0-b5fc-ad4f73fc9622)

Greetings and thanks for reading

**Comment by sisyphus** [comment]
> https://www.virustotal.com/gui/file/ecde19e9a74b5cb580c5abd9873606f4539d288a08620f7103861cc9872e4d8e/detection

I don't see anything there to be worried about - except, of course, for the reliability of avast ;-)
You're free to draw whatever conclusions you wish, but I don't think "3 out of 68" is anything to be worried about , especially when (as best as I can tell) it's really only "1 out of 68".

My understanding is that the one thing these AV vendors will try to avoid is a "false negative" - but the occasional false positive is to be treated as "forgiveable".

Anyway, I'm sure that one of the Strawberry Perl developers will reply soon.

Cheers,
Rob

**Comment by icez3r0** [comment]
if it makes sense to lower my concern now that you mention 3/68 antivirus engines, it's just that sometimes undesirable things creep into massive projects like these, and I appreciate the intention to reassure me.

**Comment by haarg** [comment]
FileRepMalware seems to just be a warning for files that haven't been seen by many Avast users. Sounds like an entirely useless warning to me.

**Comment by shawnlaffan** [comment]
The files under ```...\c\libexec\gcc``` are all sourced from the winlibs distribution.  There have been a few antivirus related issues on that project's issue tracker: https://github.com/brechtsanders/winlibs_mingw/issues?q=is%3Aissue+antivirus+

I'll close this issue now but it can be re-opened if needed.
