### ISSUE TITLE
UpgradeCpanModules step is failing since commit d714298

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/Perl-Dist-Strawberry#179]
I've just tried building Perl 5.39.10 and am hitting errors in the UpgradeCpanModules step.  

The CPANPLUS_get_upgrade_list.pl script is called using the newly built perl, but Syntax::Keyword::Try (added in commit d714298) is not a core module so does not exist at this point of the build process.  

Replacing Syntax::Keyword::Try with a standard ```eval{}``` block led to new errors.

Trying to install S::K::T using an additional InstallModules step before the UpgradeCpanModules step fails due to IPC::Run3 also not being installed, and probably others.  

I've locally reverted to an earlier commit to get the build working again.

**Comment by genio** [comment]
I thought I'd gone through that properly on my current build of 5.39.9. Let me go back through it tonight and see what I missed.

**Comment by g-bougard** [comment]
Hi,

I had the same problem on building GLPI-Agent which is based on StrawberryPerl. The build occurs in the GH Actions windows latest image context. It seems to use StrawberryPerl 5.32 and Syntax::Keyword::Try is available. I don't have an explicit error, just it fails to start the script (extract from [last failed job](https://github.com/glpi-project/glpi-agent/actions/runs/8986113741/job/24681486102)):
```
##2024/04/07-13:51:31## [step:3] starting 'UpgradeCpanModules'
    getting upgrade module list
##2024/04/07-13:51:31## BUILD FAILURE: ERROR: exec 'C:\Strawberry\perl\site\lib\auto\share\dist\Perl-Dist-Strawberry\utils\CPAN_get_upgrade_list.pl' failed at C:/Strawberry/perl/site/lib/Perl/Dist/Strawberry/Step/UpgradeCpanModules.pm line 95.
    started: zip_dir('C:\Strawberry-perl-for-GLPI-Agent_build\debug', 'C:\Strawberry-perl-for-GLPI-Agent_build\output\1715089891_debug_dir.zip', 1)
Error: Process completed with exit code 1.
```

On my windows 11 VM, I can run the script manually but I'm using StrawberryPerl 5.38.2.

**Comment by genio** [comment]
I'm going to revert that change and push this evening. My testing setup was faulty and had assumptions I didn't realize as I'd already done things to my test area that allowed this to pass in my setup

**Comment by genio** [comment]
Can you check the latest on the master branch before I cut a release, please?

**Comment by shawnlaffan** [comment]
From a build starting from a checkpoint immediately before the UpgradeCpanModules step.  

```
##2024/04/08-14:34:46## [step:3] starting 'UpgradeCpanModules'
    getting upgrade module list
##2024/04/08-14:34:47## BUILD FAILURE: Inappropriate I/O control operation at E:\shawn\sp_repos\Perl-Dist-Strawberry\blib\lib/Perl/Dist/Strawberry/Step.pm line 273.
```

I'll try with a full build and report when it gets to that point.

**Comment by shawnlaffan** [comment]
Same issue when running a full build.

**Comment by shawnlaffan** [comment]
I should have looked at the logs earlier.  It looks like the argument parsing is awry.  

```
>> started 'E:\shawn\sp_repos\Perl-Dist-Strawberry\blib\lib\auto\share\dist\Perl-Dist-Strawberry\utils\CPAN_get_upgrade_list.pl'
Unknown option: u
Unknown option: r
Unknown option: l
Unknown option: o
Unknown option: u
Unknown option: t
Unknown option: _
Unknown option: n
Unknown option: s
Unknown option: t
Unknown option: o
Unknown option: r
Unknown option: e
Unknown option: o
Unknown option: u
Unknown option: t
Unknown option: _
Unknown option: d
Unknown option: u
Unknown option: m
Unknown option: p
Unknown option: e
Unknown option: r
>> invalid option(s) at E:\shawn\sp_repos\Perl-Dist-Strawberry\blib\lib\auto\share\dist\Perl-Dist-Strawberry\utils\CPAN_get_upgrade_list.pl line 18.
```

**Comment by shawnlaffan** [comment]
Looks like we need to also revert the most recent change to this line:
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/2ba78fc83d0cc29d039b4987f85a92ff7febf376/share/utils/CPANPLUS_get_upgrade_list.pl#L7

**Comment by g-bougard** [comment]
Hi,

I confirm there's still a problem. In [my last run](https://github.com/glpi-project/glpi-agent/actions/runs/9028671669/job/24812194237), I still obtained this error:
```
 ##2024/04/10-09:06:27## [step:3] starting 'UpgradeCpanModules'
    getting upgrade module list
##2024/04/10-09:06:28## BUILD FAILURE: Inappropriate I/O control operation at C:/Strawberry/perl/site/lib/Perl/Dist/Strawberry/Step.pm line 273.
    started: zip_dir('C:\Strawberry-perl-for-GLPI-Agent_build\debug', 'C:\Strawberry-perl-for-GLPI-Agent_build\output\1715331988_debug_dir.zip', 1)
Error: Process completed with exit code 1.
```
