### ISSUE TITLE
POSIX bessel functions are broken on strawberry-perl 5.39.10.1.

### ISSUE THREAD

**Issue by sisyphus** [StrawberryPerl/Perl-Dist-Strawberry#183]
It's really a rather minor issue, IMO, but SP developers should probably be  aware of it.
No tests are failing because (AFAICS) these functions are not tested, but the bessel functions started to return garbage values when <code>-std=c99</code> was added to <code>ccflags</code> (a coupla months back).

As an example, on SP 5.38.2.2:
```
>perl -MPOSIX -wle "printf '%.17g', POSIX::j0(11.1234);"
-0.14825454045062328
```
That's not strictly accurate (the mpfr library reports -0.14825454045062314), but it's probably good enough for most purposes.

With SP 5.39.10.1, we get:
```
>perl -MPOSIX -wle "printf '%.17g', POSIX::j0(11.1234);"
-256
```

There's an "issue" (and unfolding discussion) that touches on this at https://github.com/Perl/perl5/issues/22211.
That thread is mainly about an issue specific to gcc-14, but this particular aspect of the bessel functions also affects gcc-13 and earlier if the <code>-std=c99</code> flag is included in <code>ccflags</code>.

**Comment by shawnlaffan** [comment]
Thanks for the heads up.  

Strawberry Perl does not add or remove any flags for module compilations.  This might be best dealt with in the POSIX module, which SP could patch in the build process if needed.

**Comment by sisyphus** [comment]
> Strawberry Perl does not add or remove any flags for module compilations.

The flag change I originally had in mind was to perl itself - and I know that SP is not averse to messing with perl's ccflags at the initial "Perl Build" step.

But then it became apparent that, even with that flag change, the bessel functions in POSIX would still be broken.
Those functions had, in fact, been broken since perl-5.39.7 (when <code>-std=c99</code> was added to ccflags.
The breakage had gone undetected because those functions were not tested in the test suite.

> This might be best dealt with in the POSIX module, which SP could patch in the build process if needed.

Yep - that's where it will be dealt with.

**Comment by shawnlaffan** [comment]
@sisyphus - is this still an issue for Strawberry Perl?

**Comment by sisyphus** [comment]
Yes - though if you do nothing about it, perl will still build fine and all tests will pass - as perl's test suite does not test the bessel functions.
At https://github.com/Perl/perl5/issues/22211#issuecomment-2114831908 there's a simplistic patch to POSIX.xs (which I'll be using) that restores the bessel functions to their previous (but less than perfect level of) accuracy.
It also changes  "putenv" to "_putenv" - which SP doesn't really need, but which will do no harm if enacted.

SP won't need to patch any other files so long as perl is built using gcc-13 (or earlier).

**Comment by shawnlaffan** [comment]
Thanks Rob.  

We can add that patch to the build process.  I'll keep this issue open.

**Comment by mohawk2** [comment]
Shouldn't the POSIX module add tests for the Bessel functions?

**Comment by sisyphus** [comment]
In https://github.com/Perl/perl5/issues/22211#issuecomment-2113807463, I've suggested that tests be added and I've provided a draft test script.

It's a little bit murky in that, on both Ubuntu and Windows, the implementations of the bessel functions are apparently lacking in accuracy.
At least, when compared to the results provided by the mpfr library, there's a discrepancy of up to a few ULPs.
On Windows:
```
D:\>perl -MPOSIX -le "printf '%a', POSIX::j0(11.0);"
-0x1.5e99052d216e3p-3
```
On Ubuntu:
```
$ perl -MPOSIX -le 'printf "%a\n", POSIX::j0(11.0);'
-0x1.5e99052d216dep-3
```
With the mpfr library, I get a result of -0x1.5e99052d216ddp-3:
```
D:\>perl -MMath::MPFR=":mpfr" -le "$rop = Math::MPFR->new(); Rmpfr_j0($rop, Math::MPFR->new(11), 0);printf('%a', Rmpfr_get_d($rop, 0));"
-0x1.5e99052d216ddp-3
```
(There are other values that show greater discrepancies.)
I assume that the mpfr library is returning the correct result.
@mohawk2, if you have a different trusted source, could you please  compare.

**Comment by mohawk2** [comment]
I think if people ask for the POSIX library Bessel functions, they should get them and not an error. The accuracy of the results is really a minor thing by comparison, perhaps to be noted in the docs. If the result is within even 1e-3, that seems acceptable to me.

**Comment by sisyphus** [comment]
@shawnlaffan , I assume (and hope) that SP-5.40.0.1 was built without the POSIX.xs patch applied.
It's producing rubbish for the POSIX::j0() function:
```
> perl -MPOSIX -le "for(10.5, 11.5, 12.5) {print POSIX::j0($_)}"
2
3
3
```

**Comment by shawnlaffan** [comment]
Correct.  There were no patches applied to POSIX for this build.

**Comment by sisyphus** [comment]
@tonycoz has now provided additional/improved patches (for the issues raised in https://github.com/Perl/perl5/issues/22211) at https://github.com/Perl/perl5/pull/22257.

**Comment by shawnlaffan** [comment]
We can likely apply that patch in the build process.  @genio - what do you think?

**Comment by shawnlaffan** [comment]
SP 5.40.0.1 includes the upstream patches.  Running locally gets the expected result from the [original comment](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/183#issue-2297833580).

```
perl -MPOSIX -wle "printf '%.17g', POSIX::j0(11.1234);"
-0.14825454045062328
```

I'll close this now but we can re-open if needed.
