### ISSUE TITLE
Malware detected : Win64:MalwareX-get [Trj]

### ISSUE THREAD

**Issue by denis-beurive** [StrawberryPerl/Perl-Dist-Strawberry#188]
Hello,

I've just installed Perl using the MSI installer.

AVAST immediately detected malware : see the image.

![perl-virus](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/assets/623614/95c7dd34-4541-40ef-a3f4-c4d8fe582061)

I wish you a good week.

Denis

**Comment by mohawk2** [comment]
Why does the "fichier" have a name `parl.exe` - wouldn't it be `perl.exe`?

**Comment by xenu** [comment]
@mohawk2: https://metacpan.org/dist/PAR-Packer/view/script/parl.pod

**Comment by guest20** [comment]
AVAST has a form for reporting false positives

https://www.avast.com/report-false-positive#pc

**Comment by shawnlaffan** [comment]
See also: https://github.com/rschupp/PAR-Packer/issues/80

**Comment by shawnlaffan** [comment]
As discussed above, this looks to be a false positive.  I'll close this issue in a few days unless there are reasons to keep it open.

**Comment by shawnlaffan** [comment]
Closing as noted.
