### ISSUE TITLE
Error checking in portableshell.bat is wrong

### ISSUE THREAD

**Issue by markyocom** [StrawberryPerl/Perl-Dist-Strawberry#196]
Looking at this bit of code in the INTERACTIVE section:
```
perl -MConfig -e "printf("""Perl executable: %%s\nPerl version   : %%vd / $Config{archname}\n\n""", $^X, $^V)" 2>nul
if ERRORLEVEL==1 echo FATAL ERROR: 'perl' does not work; check if your strawberry pack is complete!
```

This doesn't properly expand the value of the `ERRORLEVEL` environment variable (so it literally compares the string `ERRORLEVEL` to `1`) and should be changed to either:
```
if "%ERRORLEVEL%" == "1" echo FATAL ERROR: 'perl' does not work; check if your strawberry pack is complete!
```
...or, probably better:
```
if ERRORLEVEL 1 echo FATAL ERROR: 'perl' does not work; check if your strawberry pack is complete!
```

The former case will check to see if `perl` exits with `1`, but the second will check for any non-zero return code.

**Comment by shawnlaffan** [comment]
Thanks for noting this, but are you sure it should be ```%ERRORLEVELE%```?

https://devblogs.microsoft.com/oldnewthing/20080926-00/?p=20743

The second approach would thus seem to be better.  

It's a simple change but a PR would be welcome if you're interested.  It would need to be applied to both variants.

https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/39de5b0bb7362887239b4376b2773d17e57fa5c3/share/portable/portableshell.bat#L38
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/39de5b0bb7362887239b4376b2773d17e57fa5c3/share/portable/portableshell.pdl.bat#L45

**Comment by markyocom** [comment]
Either would work in this case (assuming your `%ERRORLEVELE%` with an extra `E` is a typo).  Comparisons are safe to do with `%ERRORLEVEL%` (per the bottom of the linked article) assuming command extensions are turned on, which they are by default in Windows.

But yes - the second approach is better in case `perl.exe` decides to exit in some nasty way that doesn't return a simple `1` for failure.

I'll see what I can do about getting a PR for you for both of those files.

**Comment by shawnlaffan** [comment]
Unfortunately the proposed change did not work in general (see #200).  

It is always possible that there were errors in implementation, in which case this can be kept open.  

I'll close this in a few days if none are raised.

**Comment by shawnlaffan** [comment]
Closing as discussed.  

Thank you again for the report, even if nothing changed in the end.
