### ISSUE TITLE
Missing files in 4.021 CPAN release

### ISSUE THREAD

**Issue by g-bougard** [StrawberryPerl/Perl-Dist-Strawberry#20]
Hi,

it seems files from the share/perl-5.32 folder are missing in the CPAN release. This involves the error like the following on the console while building perl 5.32:
```
ERROR: non-existing file 'C:\Strawberry\perl\site\lib\auto\share\dist\Perl-Dist-Strawberry\perl-5.32\win32_FindExt.pm' at C:/Strawberry/perl/site/lib/Perl/Dist/Strawberry/Step.pm line 293.
ERROR: non-existing file 'C:\Strawberry\perl\site\lib\auto\share\dist\Perl-Dist-Strawberry\perl-5.32\win32_config_H.gc' at C:/Strawberry/perl/site/lib/Perl/Dist/Strawberry/Step.pm line 293.
ERROR: non-existing file 'C:\Strawberry\perl\site\lib\auto\share\dist\Perl-Dist-Strawberry\perl-5.32\win32_config.gc.tt' at C:/Strawberry/perl/site/lib/Perl/Dist/Strawberry/Step.pm line 293.
```

**Comment by g-bougard** [comment]
Hi,

I just saw the `share/perl-5.32` folder exists in the [Perl-Dist-Strawberry-4.022.tar.gz](https://cpan.metacpan.org/authors/id/K/KM/KMX/Perl-Dist-Strawberry-4.022.tar.gz) and wasn't in Perl-Dist-Strawberry-4.021.tar.gz.

I guess this means this issue can be closed.

**Comment by kmx** [comment]
You are right, I am sorry. Fixed now.
