### ISSUE TITLE
`5.40.0.1`: Why duplicated assets in the Releases?

### ISSUE THREAD

**Issue by rwp0** [StrawberryPerl/Perl-Dist-Strawberry#201]
Why there are `_2` prefixed portable ZIP assets for the regular and PDL versions in Releases?

https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_5.40.0.1_20240803_gcc13b

![image](https://github.com/user-attachments/assets/aff47ace-3bb4-4c35-94d4-1ae094d037cb)

**Comment by shawnlaffan** [comment]
This is described under the Known Issues bullet point in the description. 
 

  * The originally uploaded portable versions do not function correctly at the moment (see https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/200). Use the variants ending in _2.zip.

**Comment by rwp0** [comment]
Thanks for the info, cannot they be deleted then from Releases?

**Comment by sisyphus** [comment]
> Not sure if deleting is possible with GitHub Releases, but that would avoid the confusion when choosing what to download.

The instructions on that page tell us to "Use the variants ending in _2.zip."
Still, I guess it would be better to remove the non-preferred version, if such is possible,

**Comment by rwp0** [comment]
> > Not sure if deleting is possible with GitHub Releases, but that would avoid the confusion when choosing what to download.
> 
> The instructions on that page tell us to "Use the variants ending in _2.zip." Still, I guess it would be better to remove the non-preferred version, if such is possible,

1. Those instruction seem to be added later, when I checked at first (and decided to download later skipping re-reading the supposedly same description) there were no instructions.
2. +1

**Comment by shawnlaffan** [comment]
I did contemplate deleting the older versions but it's only a dev release and the discussion in #200 would make less sense.  

If all goes well it will be replaced very soon.

**Comment by shawnlaffan** [comment]
5.40.0.1 builds are now available as a pre-release at https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_54001_64bit_UCRT

If they work on machines other than mine then they will be promoted to final.

**Comment by rwp0** [comment]
Thank @shawnlaffan , closing this.
