### ISSUE TITLE
Is There a false positive?

### ISSUE THREAD

**Issue by CarLos4475** [StrawberryPerl/Perl-Dist-Strawberry#205]
I scanned the version 5.40.0.1 on VirusTotal and "Ikarus" detected some trojans. here's the page: https://www.virustotal.com/gui/file/29f72c3403d316b5ec48204546a7aad6b5567ff9a346cacd94af81fe0ffdc83e/detection
Is this a false positive or something?

**Comment by shawnlaffan** [comment]
It is very likely a false positive.  See also #188

**Comment by spacestardust** [comment]
When executing the version 5.40.0.1, the anti-virus detects perlglob.exe as a trojan. 
https://www.virustotal.com/gui/file/6494440e376a6caeb8fdb3c2a38c00249b126534008fcd8f0f2efcbdf7dfb6cd/detection

**Comment by xenu** [comment]
We can't really do anything about this.

Anti-Virus vendors make it unreasonably hard to report false positives. They often require you to register, prove that you're their client blah blah

It feels like ensuring high false positive rate is their number one priority.
