### ISSUE TITLE
[feature request] Use Github Releases as an unofficial mirror

### ISSUE THREAD

**Issue by BillyONeal** [StrawberryPerl/Perl-Dist-Strawberry#21]
`vcpkg` needs to make a perl available in order to build `openssl`, so we're sending a fair bit of traffic over to your servers. This has resulted in some folks complaining about taking a very long time to download StrawberryPerl. For example https://github.com/microsoft/vcpkg/issues/14280

Would it be possible to use GitHub releases as an additional mirror? Asking only because you're apparently already here on GitHub :)

Thanks for such a fantastic distribution!

**Comment by kmx** [comment]
I have not investigated the current situation but in the past github was not friendly to huge binary release packages. Complete mirror currently means 54GB of MSI/ZIP files.

**Comment by BillyONeal** [comment]
I see, I was under the impression that it was much smaller ¯\_(ツ)_/¯.

Thanks for the consideration nonetheless!

**Comment by PhilLab** [comment]
@kmx Thanks for your work on the dist and for your response! Would it be possible to take a second look? The connection is indeed very slow (sometimes ~200kbit/s , sometimes ~50kbit/s) at least at my location.

**Comment by BillyONeal** [comment]
@PhilLab I think given that vcpkg only wants a small subset of the project (that being the installer) we might need to run our own mirror somehow.

**Comment by BillyONeal** [comment]
@PhilLabI just spoke with other vcpkg folks and they indicated that mirroring isn't as straightforward (for licensing reasons) as we might like so I doubt anything will change soon.
