### ISSUE TITLE
Error during Tk installation

### ISSUE THREAD

**Issue by JMFR22** [StrawberryPerl/Perl-Dist-Strawberry#212]
OS: Windows 11 ('ver' command returned "Microsoft Windows [version 10.0.22631.4037]")
With Strawberry Perl (64-bit) Portable 5.40.0.1-64bit, in cpan i did "install Tk" and got the error below:
 gcc -c -I. -I./pTk/mTk/xlib  -I.. -I.. -I../pTk/mTk/xlib -I. -Ibitmaps -I.. -I../pTk/mTk/xlib -std=c99 -DWIN32 -DWIN64 -DPERL_TEXTMODE_SCRIPTS -DMULTIPLICITY -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fwrapv -fno-strict-aliasing -mms-bitfields -DPERLDLL -Os -falign-functions -falign-jumps -falign-labels -falign-loops -freorder-blocks -freorder-blocks-algorithm=stc -freorder-blocks-and-partition   -DVERSION=\"804.036\" -DXS_VERSION=\"804.036\"  "-IC:\Strawberry\perl\lib\CORE"    imgBMP.c
In file included from ../pTk/mTk/xlib/X11/Xlib.h:31,
                 from tkWinPort.h:19,
                 from tkPort.h:32,
                 from tk.h:87,
                 from imgBMP.c:11:
../pTk/mTk/xlib/X11/X.h:182:34: error: expected identifier or '(' before numeric constant
  182 | #define ControlMask             (1<<2)
      |                                  ^
gmake[1]: *** [makefile:891: imgBMP.o] Error 1
gmake[1]: Leaving directory 'C:/Strawberry/cpan/build/Tk-804.036-0/pTk'
gmake: *** [makefile:1638: pTk/libpTk.a] Error 2
  SREZIC/Tk-804.036.tar.gz
  C:\Strawberry\c\bin\gmake.exe -- NOT OK
Stopping: 'install' failed for 'Tk'.
Failed during this command:
 SREZIC/Tk-804.036.tar.gz                     : make NO

**Comment by shawnlaffan** [comment]
A patched version of Tk is available.  See https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/87#issuecomment-2292839449

**Comment by shawnlaffan** [comment]
@JMFR22 - I'll close this issue now but please comment if there is reason to keep it open.
