### ISSUE TITLE
Virus in strawberry-perl-5.32.0.1-64bit.msi?

### ISSUE THREAD

**Issue by misterjoshua** [StrawberryPerl/Perl-Dist-Strawberry#22]
I scanned the recommended .msi installer distributed from the website with VirusTotal and CRDF detected some sort of malicious software. 

File on the website: https://strawberryperl.com/download/5.32.0.1/strawberry-perl-5.32.0.1-64bit.msi
Virus total: https://www.virustotal.com/gui/url/e30fff6adc317ef3eb37867bd9fb4c9d1d2fbb8aa3dceddabe0a8f309dc56a49/details

Is this a false positive?

**Comment by rai-gaurav** [comment]
Without a doubt yes. Similar issue was reported for berry brew at - https://github.com/stevieb9/berrybrew/issues/241 and one solution is mentioned there (reaching out to specific vendor).
But I would not worry much as top vendors are saying its clean. 
I checked some previous strawberry Perl version also and for all of then the same antivirus is detecting it. So it is something specific to only that vendor. I checked the downloaded file sha also but none of them is detecting it. Perfect clean.
