### ISSUE TITLE
Virus or falsepositive?

### ISSUE THREAD

**Issue by ArcherTannic** [StrawberryPerl/Perl-Dist-Strawberry#223]
I installed perl strawberry-perl-5.40.0.1-64bit
and my antivirus malwarybates say me in perl virus 
so i upload in virustotal and see it 
[https://www.virustotal.com/gui/file/8c1d790b9bb1bca0b5cf1b3432226d9c7ebe32505275c53d0877b8351fb62668?nocache=1](url)

I open bin and add all  files inot zip archive and upload in virustotal
So its falsepositive or not?

**Comment by guest20** [comment]
Its likely a false positive, there are lots of closed issues with similar reports.

You can always build from source if your unsure.

**Comment by shawnlaffan** [comment]
See also https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues?q=label%3Aantivirus+

**Comment by shawnlaffan** [comment]
There have been no updates for about six weeks.  I'll close this issue now.
