### ISSUE TITLE
in strawbarry  5.40.0.1 MSI  impossible install TK

### ISSUE THREAD

**Issue by faustf** [StrawberryPerl/Perl-Dist-Strawberry#225]
Hi, I installed the latest version of Strawberry, and I tried to install TK, but it gives me an error. I also tried GTK, QT, and WX, but they also give installation errors. I installed everything using CPAN.I’m interested in getting TK to work. anyone can help me ?
tk error
`gcc -c -I. -I./pTk/mTk/xlib  -I.. -I.. -I../pTk/mTk/xlib -I. -Ibitmaps -I.. -I../pTk/mTk/xlib -std=c99 -DWIN32 -DWIN64 -DPERL_TEXTMODE_SCRIPTS -DMULTIPLICITY -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fwrapv -fno-strict-aliasing -mms-bitfields -DPERLDLL -Os -falign-functions -falign-jumps -falign-labels -falign-loops -freorder-blocks -freorder-blocks-algorithm=stc -freorder-blocks-and-partition   -DVERSION=\"804.036\" -DXS_VERSION=\"804.036\"  "-IC:\STRAWB~1\perl\lib\CORE"    imgBMP.c
In file included from ../pTk/mTk/xlib/X11/Xlib.h:31,
                 from tkWinPort.h:19,
                 from tkPort.h:32,
                 from tk.h:87,
                 from imgBMP.c:11:
../pTk/mTk/xlib/X11/X.h:182:34: error: expected identifier or '(' before numeric constant
  182 | #define ControlMask             (1<<2)
      |                                  ^
gmake[1]: *** [makefile:891: imgBMP.o] Error 1
gmake[1]: Leaving directory 'C:/STRAWB~1/cpan/build/Tk-804.036-2/pTk'
gmake: *** [makefile:1638: pTk/libpTk.a] Error 2
  SREZIC/Tk-804.036.tar.gz
  C:\STRAWB~1\c\bin\gmake.exe -- NOT OK
Stopping: 'install' failed for 'Tk'.
`

**Comment by sisyphus** [comment]
There's a fixed version.
See https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/87#issuecomment-2292839449

**Comment by shawnlaffan** [comment]
I'll close this issue now given there have been no additional comments for several weeks.
