### ISSUE TITLE
Installing Perl Language Server on Strawberry fails

### ISSUE THREAD

**Issue by sumanstats** [StrawberryPerl/Perl-Dist-Strawberry#27]
I am trying to install [Perl Language server](https://metacpan.org/pod/Perl::LanguageServer) in strawberry perl to get IDE support in VS Code.

When I try to install it with 
`cpanm Perl::LanguageServer` I get this failed message:

```
--> Working on Perl::LanguageServer
Fetching http://www.cpan.org/authors/id/G/GR/GRICHTER/Perl-LanguageServer-2.2.0.tar.gz ... OK
Configuring Perl-LanguageServer-v2.2.0 ... OK
==> Found dependencies: AnyEvent::AIO, IO::AIO
--> Working on AnyEvent::AIO
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/AnyEvent-AIO-1.1.tar.gz ... OK
Configuring AnyEvent-AIO-1.1 ... OK
==> Found dependencies: IO::AIO
--> Working on IO::AIO
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/IO-AIO-4.75.tar.gz ... OK
Configuring IO-AIO-4.75 ... OK
Building and testing IO-AIO-4.75 ... FAIL
! Installing IO::AIO failed. See C:\strawberry-perl-5.32.1.1-64bit-PDL\data\.cpanm\work\1622910817.18144\build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'IO::AIO' is not installed
! Bailing out the installation for AnyEvent-AIO-1.1.
! Installing the dependencies failed: Module 'AnyEvent::AIO' is not installed, Module 'IO::AIO' is not installed
! Bailing out the installation for Perl-LanguageServer-v2.2.0.
```

Again I tried installing with `--force`

`cpanm --force Perl::LanguageServer` but doesn't work either.

```
--> Working on Perl::LanguageServer
Fetching http://www.cpan.org/authors/id/G/GR/GRICHTER/Perl-LanguageServer-2.2.0.tar.gz ... OK
Configuring Perl-LanguageServer-v2.2.0 ... OK
==> Found dependencies: AnyEvent::AIO, IO::AIO
--> Working on AnyEvent::AIO
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/AnyEvent-AIO-1.1.tar.gz ... OK
Configuring AnyEvent-AIO-1.1 ... OK
==> Found dependencies: IO::AIO
--> Working on IO::AIO
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/IO-AIO-4.75.tar.gz ... OK
Configuring IO-AIO-4.75 ... OK
Building and testing IO-AIO-4.75 ... FAIL
! Installing IO::AIO failed. See C:\strawberry-perl-5.32.1.1-64bit-PDL\data\.cpanm\work\1622911059.17340\build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'IO::AIO' is not installed
! Bailing out the installation for AnyEvent-AIO-1.1.
! Installing the dependencies failed: Module 'IO::AIO' is not installed, Module 'AnyEvent::AIO' is not installed
! Bailing out the installation for Perl-LanguageServer-v2.2.0.
```

Any solution to get around this so that I can use VS Code as Perl development environment.

**Comment by genio** [comment]
@sumanstats Hi! This isn't really a problem with Strawberry Perl and I'd suggest we close this out. The author or IO::AIO and AnyEvent::* doesn't support Windows. You might do better to reach out there and see if the author can do anything to begin supporting Windows.

**Comment by karenetheridge** [comment]
As indicated in the output, the build.log will contain more information as to the nature of the failures. Even if Strawberry Perl was at fault here, the necessary information to diagnosing the problem will be contained in that file.

**Comment by shawnlaffan** [comment]
Issues with external modules should generally be reported to their respective bug queues.  

FWIW, AnyEvent has not built on many systems for some time.  
http://matrix.cpantesters.org/?dist=AnyEvent+7.17

Perl Language Server also has this note on the topic:
https://metacpan.org/pod/Perl::LanguageServer#AnyEvent%2C-Coro-Warning-during-install

**Comment by mohawk2** [comment]
There's an issue on the P:LS repo: https://github.com/richterger/Perl-LanguageServer/issues/198

**Comment by peter1206xx** [comment]
> Update: I was able to install `AnyEvent` on Strawberry Perl just fine.

Very interesting! Question: t/80_ssltest.t was succesful? Nothing like:?
```
# Failed test 'server_error <Eine bestehende Verbindung wurde softwaregesteuert
# durch den Hostcomputer abgebrochen.>'
# at t/80_ssltest.t line 37
```
