### ISSUE TITLE
"choco install strawberryperl" fails on mswin/appveyor

### ISSUE THREAD

**Issue by shlomif** [StrawberryPerl/Perl-Dist-Strawberry#29]
Hi all! how can i fix "choco install strawberryperl" on mswin/appveyor: 

https://ci.appveyor.com/project/shlomif/fc-solve/builds/40215398

```
choco install strawberryperl
Chocolatey v0.10.15
Installing the following packages:
strawberryperl
By installing you accept licenses for the packages.
Progress: Downloading StrawberryPerl 5.32.1.1... 100%
StrawberryPerl v5.32.1.1 [Approved]
strawberryperl package files install completed. Performing other installation steps.
Downloading strawberryperl 64 bit
  from 'https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit.msi'
Progress: 100% - Completed download of C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\StrawberryPerl\5.32.1.1\strawberry-perl-5.32.1.1-64bit.msi (103.26 MB).
Download of strawberry-perl-5.32.1.1-64bit.msi (103.26 MB) completed.
Hashes match.
Installing strawberryperl...
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\StrawberryPerl_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\StrawberryPerl\5.32.1.1\strawberry-perl-5.32.1.1-64bit.msi" /qn /norestart ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\StrawberryPerl_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
The install of strawberryperl was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\StrawberryPerl\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
 - strawberryperl (exited 1603) - Error while running 'C:\ProgramData\chocolatey\lib\StrawberryPerl\tools\chocola
```

appveyor.yml is in https://github.com/shlomif/fc-solve/blob/67c848508a3eaefc42605d2ff0828cf18c2085ea/.appveyor.yml

**Comment by genio** [comment]
The setup for AppVeyor isn't quite right and takes quite a bit of effort to get right. I'd suggest using GitHub workflows instead. For an example: https://github.com/p5-UV/p5-UV/blob/master/.github/workflows/windows.yml

**Comment by genio** [comment]
Our older AppVeyor setup can be seen here:
https://github.com/p5-UV/p5-UV/blob/v1.908/.appveyor.cmd
https://github.com/p5-UV/p5-UV/blob/v1.908/.appveyor.yml

**Comment by shlomif** [comment]
> The setup for AppVeyor isn't quite right and takes quite a bit of effort to get right. I'd suggest using GitHub workflows instead. For an example: https://github.com/p5-UV/p5-UV/blob/master/.github/workflows/windows.yml

thanks @genio !

Can that `.yml` be relicensed under the MITL, or can one provide a similar one? see https://www.shlomifish.org/philosophy/computers/open-source/foss-licences-wars/indiv-nodes/which-licence-same-as-perl.xhtml .

**Comment by genio** [comment]
I don't know that there's anything particularly proprietary there. All we are doing is using the basic examples from https://github.com/shogo82148/actions-setup-perl  and running some cpanm commands.

**Comment by genio** [comment]
@shlomif I think this can be closed since https://github.com/shogo82148/actions-setup-perl#use-strawberry-perl-on-windows is released under MIT and our UV workflow YAML file is nothing short of a copy of their example with more installations via cpanm.

**Comment by shlomif** [comment]
Hi,

On Thu, 05 Aug 2021 05:18:20 -0700
Chase Whitener ***@***.***> wrote:

> @shlomif I think this can be closed since
> https://github.com/shogo82148/actions-setup-perl#use-strawberry-perl-on-windows
> is released under MIT and our UV workflow YAML file is nothing short of a
> copy of their example with more installations via cpanm.
> 

Do it then. Thanks!

-- 

Shlomi Fish       https://www.shlomifish.org/
List of Text Processing Tools - https://shlom.in/text-proc

When people agree with me I always feel I must be wrong.
    — https://en.wikiquote.org/wiki/Oscar_Wilde (via fortune-mod)

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
Closing per agreement.
