### ISSUE TITLE
Is the OpenSSL version distributed with Strawberry Perl (via Chocolatey) up to date?

### ISSUE THREAD

**Issue by SomeoneElseOSM** [StrawberryPerl/Perl-Dist-Strawberry#31]
Within here it appears that there's an OpenSSL version distributed:
C:\Strawberry\c\bin\openssl.exe
OpenSSL> version
OpenSSL 1.1.1i  8 Dec 2020

According to https://www.openssl.org/news/vulnerabilities-1.1.1.html , this seems to be not the latest.

Is this something that could do to be updated, or have I got hold of the wrong end of the stick and the openssl.exe in "Strawberry\c\bin\openssl.exe" isn't coming from here?

**Comment by shawnlaffan** [comment]
The next release of Strawberry Perl will include a more recent version of OpenSSL.  

If you want to try the current dev release then see https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_5361_20230524_gcc13
