### ISSUE TITLE
Can 32bit Strawberry Perl be installed into Windows using Chocolatey

### ISSUE THREAD

**Issue by yuki-kimoto** [StrawberryPerl/Perl-Dist-Strawberry#33]
Can 32bit Strawberry Perl be installed into Windows using Chocolatey?

**Comment by genio** [comment]
I'm not 100% certain if chocolatey allows installing a 32-bit software title if you've got a 64-bit version of Chocolatey installed and vice-versa. 

Maybe they have some forums somewhere that discuss that? My guess would be to try with the version parameter and use 5.14.4.1-32bit or some such like that. 

Sorry I don't know more about Chocolatey to be of much help.

**Comment by yuki-kimoto** [comment]
>Sorry I don't know more about Chocolatey to be of much help.

Isn't the Strawberry Perl on chocolatey released by the Strawberry Perl team?

https://community.chocolatey.org/packages/StrawberryPerl

**Comment by bekuno** [comment]
Please have a look at the maintainer entry.
Following them you will find https://github.com/Thilas/chocolatey-packages/tree/master/strawberryperl

**Comment by yuki-kimoto** [comment]
@bekuno

Thank you. I will ask this question to the maintainers.

**Comment by shawnlaffan** [comment]
I think is resolved?  I'll close it now but please comment if it needs further responses from the Strawberry perl end.
