### ISSUE TITLE
Please pull latest Win32::OLE::Const package into Strawberry Perl...

### ISSUE THREAD

**Issue by Tronmech** [StrawberryPerl/Perl-Dist-Strawberry#36]
When attempting to access a 64-bit MS Outlook instance to send a mail message (or do anything else in Outlook), this error occurs:
No type library matching "Microsoft Outlook" found at .\testmail2.pl line 4.
Win32::OLE(0.1712): GetOleTypeLibObject() Not a Win32::OLE::TypeLib object at C:/Strawberry/perl/vendor/lib/Win32/OLE/Const.pm line 49.

When line 4 reads:
use Win32::OLE::Const 'Microsoft Outlook';

This is a known issue and, according to this github link https://github.com/jandubois/win32-ole/pull/9 is resolved. The release with the issue resolved is at: https://metacpan.org/release/JDB/Win32-OLE-0.1713

There are multiple CPAN packages that use this. Including Mail::Outlook, which is how I wound up going down this rathole in the first place as that error message is also in a a Mail::Outlook issue

**Comment by sisyphus** [comment]
@Tronmech, are you aware that you can update Win32::OLE to the latest version on  your current Strawberry installation by running <code>cpan -i Win32::OLE</code> ?

I think the latest version of Win32::OLE will be included in the *next* release of Strawberry Perl, but I wouldn't expect that existing Strawberry packages will ever be updated to Win32-OLE-0.1713.

**Comment by Tronmech** [comment]
Yes, I was able to do that, but I work in software development... My experience has been that if there isn't an "issue/defect/request" in the queue... There is no guarantee that this will happen...

**Comment by shawnlaffan** [comment]
@Tronmech - The next release of Strawberry Perl will include Win32::OLE 0.1713.  

If you want to give it a try the current dev version for perl 5.36 can be obtained from https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_20230420

We have yet to build 5.34 but versions prior to that are unlikely to see new releases.  As @sisyphus notes, users can update that themselves using one of the available cpan clients.  

I'll close this issue in a few days.

**Comment by shawnlaffan** [comment]
Somewhat more than a few days, but closing now.
