### ISSUE TITLE
Installation incomplete (?) on Windows 7 (?)

### ISSUE THREAD

**Issue by ChrisChiesa** [StrawberryPerl/Perl-Dist-Strawberry#38]
I just installed Strawberry Perl on what I _think_ is Windows 7 (the "OS version" string is blank, everywhere I should be able to pull up that information), 64-bit.  I installed by downloading the 64-bit Windows **.msi** file, running the command prompt (**cmd**) "as Administrator," going to the folder where the .msi file landed, and typing its name at the prompt.  This appeared to succeed, in that I can run a Perl script by typing its name at the command prompt; I have not yet tried double-clicking its icon in Windows Explorer.   However, I quickly subsequently observed the following issues:

1. Using **perl -d _scriptfilename**_ to run a script under the Perl debugger works -- but first it puts up about thirty lines of error messages, starting with "Unable to get Terminal Size. The Win32 GetConsoleScreenBufferInfo call didn't work. The COLUMNS and LINES environment variables didn't work. at C:/Strawberry/perl/vendor/lib/Term/ReadLine/readline.pm line 410."  

2. The command **perldoc -f _functionname**_ does not work, as such; I find that the Strawberry Perl binary directory (C:\Strawberry\Perl\bin) is not in the PATH variable -- this, in the same Command window from which I installed Strawberry Perl.  (The command _does_ work , when I fully specify the path: **C:\Strawberry\Perl\bin\perldoc -f _scriptfilename**_ .

3. As a longtime user of the _other_ popular Perl package for Windows, I have gotten used to either Perl/Tk or Tkx being bundled, such that it is available immediately upon installation.  I find that this is not so in this instance.  Is this normal behavior?

Generally, it looks as though a number of "environmental" settings (the COLUMNS and LINES variables; addition of the bin directory to the PATH) have _not taken place_ in this installation.  Did I do something wrong?  Did I neglect to execute a subsidiary setup script or something?  Please advise.

**Comment by sisyphus** [comment]
It's a bit sad that no-one had got back to you  about this.
My preference is for the "portable" releases (which neither require nor expect Admin privileges), rather than the ".msi" ones, and I'm not all that knowledgeable about those msi releases.

C:\Strawberry\Perl\bin should definitely be in the PATH environment variable - but at the very end of it.
Perhaps it's there and you've missed seeing it ?
When you invoke "perl" on the command line, the perl that gets loaded will be the first one found in the PATH.
Is there another perl currently in your PATH ? 

It's normal that Tk and Tkx are not bundled with Strawberry Perl.
On a properly functioning Strawberry Perl you would install Tk with:
```
cpan -i Tk
```
though you might need to attend to the Tk bug detailed at:
https://rt.cpan.org/Public/Bug/Display.html?id=133260
(Let us know if you need some help with that part.)

I don't know how readily Tkx can be installed.

Cheers,
Rob

**Comment by ChrisChiesa** [comment]
Not to worry -- as you can see, it has taken me _much longer than that_ to get back here to even _see_ if anybody has replied.  Thank you for replying.

I don't know how to pick-and-choose which release(s) I install -- I go to wherever Google tells me Strawberry Perl lives, and I pick whatever is available, and I don't expect to have much choice in the matter.  Please enlighten me as to how to take more agency on this, as I have a couple other computers on which I'd also like to install Strawberry Perl.

It seems that at least one of the problems I originally complained of, has spontaneously resolved itself: I can now successfully issue a **perldoc -f _functionname**_ command, and it works.    This seems to be because I do now see C:\Strawberry\perl\bin in my PATH.
I still have the problem, however, of the thirty-lines-of-errors when entering the Debugger.  Don't know what to do about that, or how the missing symbols are supposed to get defined.

Thanks again for your help.

**Comment by sisyphus** [comment]
> I still have the problem, however, of the thirty-lines-of-errors when entering the Debugger.

Yes, I see the same but I don't know what to do about it either.
I don't use the perl debugger, so it's not really a problem for me.
I suspect that it's probably functioning ok, in spite of all the noise that gets made.
You might get good help about this over at perlmonks (https://www.perlmonks.org/?node=Seekers%20of%20Perl%20Wisdom) if no-one here steps up with some assistance.

You'll find all of the Strawberry Perl releases at https://strawberryperl.com/releases.html .
As I said, I prefer the "portable" releases.
Just unpack your chosen portable release into some directory, execute the portableshell.bat that's in that drectory and the shell that opens up is all set to go.
You can have multiple versions of "portable" Strawberry Perl on your system - so long as they have been unpacked into separate locations.

Cheers,
Rob

**Comment by shawnlaffan** [comment]
The debugger issue seems to be more generic than Strawberry perl and can be worked around by setting TERM=dumb before calling perl.  

```
set TERM=dumb
perl -d somescript.pl
```

https://stackoverflow.com/questions/54324750/cpan-error-unable-to-get-terminal-size-the-win32-getconsolescreenbufferinfo-ca

**Comment by shawnlaffan** [comment]
I'll close this on the basis it is not a problem specific to Strawberry perl.  Please re-open if that's incorrect.
