### ISSUE TITLE
a fixed bug in the GNU Readline Library 8.0

### ISSUE THREAD

**Issue by hirooih** [StrawberryPerl/Perl-Dist-Strawberry#44]
There is a known bug only for the MSYS2 and MSWin32 in the GNU Readline Library 8.0 distributed with the Strawberry Perl.
https://lists.gnu.org/archive/html/bug-readline/2019-04/msg00000.html
The bug has already been fixed in version 8.1 (and the latest 8.2, of course).

Is there a plan to update and release the Strawberry Perl distribution in the near feature?

***

Background to the question:

I'm the author of `Term::ReadLine::Gnu` module.  Last week I received fail reports showing it was possible to build the XS module  the Strawberry Perl, and it was working although it produced some errors.

> Term-ReadLine-Gnu-1.44:
> - MSWin32-x64-multi-thread / 5.32.1:
>   - FAIL http://www.cpantesters.org/cpan/report/73e75569-6d21-1014-8029-cb3c53d16864
> - MSWin32-x86-multi-thread-64int / 5.32.1:
>   - FAIL http://www.cpantesters.org/cpan/report/584d4dee-6c09-1014-99e7-7710a1847d30

It was great news for me.
Last weekend I downloaded and installed the Strawberry Perl.  And I made some fixes for it and I am ready to release. But `gmake test` still fails due to the bug above.

I would like to know the release plan of this project to write the release note of my moudle.

**Comment by hirooih** [comment]
Sounds great!
Thanks.

**Comment by shawnlaffan** [comment]
@hirooih - there are now 5.36.1 dev releases available.  These include readline 8.2.  
Latest is at https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_5.36.1_20230528_gcc13

Term::ReadLine::Gnu passes its tests using that version.

I'll close this issue in a few days unless there are reports of failures.

**Comment by hirooih** [comment]
@shawnlaffan 

> Term::ReadLine::Gnu passes its tests using that version.

I also have confirmed that the all test passes in my environment.
I am looking forward to the official release. Thank you for your great works!

**Comment by shawnlaffan** [comment]
@hirooih - thanks for confirming.  I'll close this issue now.
