### ISSUE TITLE
Can't access strawberryperl.com

### ISSUE THREAD

**Issue by kanithinon** [StrawberryPerl/Perl-Dist-Strawberry#45]
Dear sir.,

I can't access strawberryperl.com from IP 110.49.74.94. please resolve my problem.

Kanit

**Comment by aborisovich** [comment]
Reproduced...

**Comment by genio** [comment]
It's now down for me as well. We're looking into it

**Comment by kanithinon** [comment]
Dear Chase Whitener.,
I can't accessed strawberryperl.com website. My ISP told me about you may be block my real ip.
Please solve this problem for me.
Best regard.Kanit Hin-onIT SupportVisionNet Co., Ltd.66813002870
    On Tuesday, November 29, 2022 at 11:17:59 PM GMT+7, Chase Whitener ***@***.***> wrote:  
 
 


Closed #45 as completed.
