### ISSUE TITLE
 MSVC (14.2) error LNK2019: unresolved external symbol __builtin_expect

### ISSUE THREAD

**Issue by cuguardo** [StrawberryPerl/Perl-Dist-Strawberry#47]
Please, remove #define HAS_BUILTIN_EXPECT from _perl/lib/CORE/config.h_ for Windows platform. 
There are no _likely_ and _unlikely_ builtin functions in VC runtime.

**Comment by genio** [comment]
Hi @cuguardo I think this is most likely something that should be reported on the Perl repository if it's an issue. I'll ask some of the proper folks to take a look.

**Comment by genio** [comment]
Side note, Strawberry is not built using MSVC. The MSVC compiler and tooling can't be used because it would force many users of Strawberry Perl to license MSVC in order to successfully use Perl.

**Comment by genio** [comment]
Hi @cuguardo!

Curiosity question: Are you trying to build an XS module with Strawberry Perl using MSVC? You'll likely run into many issues this way since we have to build Strawberry with MSYS2+MinGW.

**Comment by sisyphus** [comment]
AFAICS, my own builds of perl on Windows have never defined <code>HAS_BUILTIN_EXPECT</code>.
The SP builds of perl are apparently doing something (presumably hacking win32/Config_H.gc) to define it.
@genio, do you know why that is being done ?
@cuguardo, I too am curious to learn details about the problem you are having.

Cheers,
Rob

**Comment by shawnlaffan** [comment]
Looks like it is defined in 5.30 and 5.32.
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/9964565ffab435a62bc35f3787174b01f8de5959/share/perl-5.32/diffs_for_info_only/win32_config_H.gc.diff
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/9964565ffab435a62bc35f3787174b01f8de5959/share/perl-5.30/diffs_for_info_only/win32_config_H.gc.diff

Found using https://github.com/search?q=org%3AStrawberryPerl+HAS_BUILTIN_EXPECT&type=code

**Comment by sisyphus** [comment]
> Looks like it is defined in 5.30 and 5.32.

I guess the same hack will be applied to 5.34 and 5.36 ?
Anyway, the interesting thing would be to learn how this has caused problems for @cuguardo .
It has never been an issue for me, and AFAIK it hasn't posed problems for others (apart from @cuguardo).

Cheers,
Rob

**Comment by cuguardo** [comment]
Actually I used Strawberry Perl to build and test a PostgreSQL on Windows. There is a built-in pl/perl language for writing stored procedures and so on. You will need the perl library to build it. 
IMHO because the CORE/config.h header is included when building under Windows, it should be aware of that platform's specifics and toolset. More or less like this:
#ifndef_MSC_VER
# define HAS_BUILTIN_EXPECT /**/
#endif _MSC_VER

**Comment by cuguardo** [comment]
The pl/perl code uses, among others, the SvREFCNT_dec function defined as follows in CORE/inline.h:
```
PERL_STATIC_INLINE void
Perl_SvREFCNT_dec(pTHX_ SV *sv)
{
    if (LIKELY(sv != NULL)) {
	U32 rc = SvREFCNT(sv);
	if (LIKELY(rc > 1))
	    SvREFCNT(sv) = rc - 1;
	else
	    Perl_sv_free2(aTHX_ sv, rc);
    }
}
```
And LIKELY is unconditionally defined using __builtin_expect

**Comment by sisyphus** [comment]
>
 ```
#ifndef_MSC_VER
# define HAS_BUILTIN_EXPECT /**/
#endif _MSC_VER
```
Are you saying that this change alone will fix your issue ?
I can't think of any reason that the Strawberry Perl developers should object to that alteration if it's going to help someone.
(That's easy for me to say, of course ;-)

> The pl/perl code uses, among others, the SvREFCNT_dec function defined as follows in CORE/inline.h

I don't understand your point.
It looks to me that the SvREFCNT_dec function in CORE/inline.h is exactly the same for MSVC-built perls (which don't define <code>HAS_BUILTIN_EXPECT</code>) as it is for Strawberry Perl (which *does* define <code>HAS_BUILTIN_EXPECT</code>.
 
Cheers,
Rob

**Comment by cuguardo** [comment]
The root cause of the problem I encoutered are __builting_expect calls in code that compiles with MSVC. I solved it as described in my comments above. This turned out to be enough.
If you are interested, I can briefly explain: the PL/perl module code defines an SPI (Server Programming Interface) on the postgresql side for the perl interpreter, so that some internal entities of the DB server become available to the perl program. Inside the SPI, the API functions defined in the perl headers only are used. The module does not linked directly with perl5XX.dll.

I tried to replace ActivePerl with StrawberryPerl in our project, and I basically succeeded.
To make or not to make any changes is up to you, I'm just one of the PostgresPRO developers and I can only express my point of view on how it should be, and nothing more.
In any case, thanks for your attention! :)

**Comment by tonycoz** [comment]
> Please, remove #define HAS_BUILTIN_EXPECT from _perl/lib/CORE/config.h_ for Windows platform.
> There are no _likely_ and _unlikely_ builtin functions in VC runtime.

Perl built with MSVC doesn't define `HAS_BUILTIN_EXPECT`, if you want to build XS modules with MSVC, you'll need to use a perl built with MSVC (which strawberry isn't).

**Comment by shawnlaffan** [comment]
FWIW, ```BUILTIN_EXPECT``` is disabled in the 5.36 builds.  See #85 for details.

I think this issue can be closed?

**Comment by NeedsMoar** [comment]
> Side note, Strawberry is not built using MSVC. The MSVC compiler and tooling can't be used because it would force many users of Strawberry Perl to license MSVC in order to successfully use Perl.

No longer the case as per [Microsoft's 8/30/2022 Licensing Change](https://devblogs.microsoft.com/cppblog/updates-to-visual-studio-build-tools-license-for-c-and-cpp-open-source-projects/).

**Comment by genio** [comment]
Yes, we worked towards that end with them for a while: https://developercommunity.visualstudio.com/t/CC-compiler-and-linker-free-CLI-only/10042178

They had updated license files but not on the site, so it wasn't actually apparent for quite some time.

While we're currently working on an MSYS2/MinGW release of Strawberry, another goal is being worked towards to have MSVC releases happen soon. A lot of tooling will need to be figured out for that process. Most things install with ExtUtils::MakeMaker which creates a `makefile` and runs it. Ensuring EUMM generates makefiles compatible with MSVC will be a thing. There will be lots of gotchas to figure out in that process.

**Comment by sisyphus** [comment]
> Ensuring EUMM generates makefiles compatible with MSVC will be a thing.

Perl-5.36.0 and later (including devel releases) build straight out of the box with VS-2022, using nmake.
Such compatibility issues should simply not exist - and will be very rare at worst.

Building the 3rd party libraries used by some of the  "vendor" modules might be challenging, even hair-reducing,
But you shouldn't have to patch anything in EUMM - though you might have to amend some of the directives being passed to EUMM from some Makefile.PL files.
(I don't know of any such Makefile.PL, but there's a lot of them on the CPAN that I can't vouch for ;-)

Cheers,
Rob

**Comment by shawnlaffan** [comment]
As noted above, ```HAS_BUILTIN_EXPECT``` is no longer part of the build system.  I'll close this issue now.
