### ISSUE TITLE
PATH on Windows ?

### ISSUE THREAD

**Issue by thistlillo** [StrawberryPerl/Perl-Dist-Strawberry#48]
I have just installed:
https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit.msi
on Microsoft Windows 11 (Pro).

I installed it in my user folder (not system-wide). At the end of the installation, the perl binary is not in the PATH. 

Why did you not update the PATH env var?

**Comment by genio** [comment]
It _should_ be in your `PATH` at this point. That's one of the installer's steps.

If you installed in `C:\Users\foo\perl` then you would need to add these paths to your `PATH`

```
C:\Users\foo\perl\perl\site\bin
C:\Users\foo\perl\perl\bin
C:\Users\foo\perl\c\bin
```

**Comment by thistlillo** [comment]
Yes, you are right. The correct path was there. However, the usual clore/open Terminal did not work at all. I had to reboot: I am working on a new Windows 11 PC and I am encountering the weirdest behaviour of all times. Thanks!
