### ISSUE TITLE
perl include does not find file

### ISSUE THREAD

**Issue by pizzazz99** [StrawberryPerl/Perl-Dist-Strawberry#50]
Hi

Regarding strawberry perl....

I am submitting a "perl -I <path to source file> and the interpreter says it cannot find the module.  The module is a perl ".pm"
source file that contains a package source code.

I do not know why the -I is returning an error.

I am sure it is something stupid on my part.

Thanks

**Comment by pizzazz99** [comment]
Sorry.  Close this request.  I am an IDIOT!!!!!!!

**Comment by genio** [comment]
heh. No worries at all. If I had a dollar for every time I shouted "Ah, I'm an idiot!" I'd be a rich person.
