### ISSUE TITLE
missing file openssl.cnf needed by openssl.exe

### ISSUE THREAD

**Issue by LorenzoTa** [StrawberryPerl/Perl-Dist-Strawberry#51]
Hello,

I noticed this error also in the past and with different straberry portable editions, actually it shows up with latest version: Strawberry Perl 5.32.1.1 (2021-01-24)

The error happens only parsing _some_ CSR or this is my memory about this. I cannot share these CSRs sadly, if really needed I can share some properties of them. let me know in case.

The error comes running a command like: `openssl req -noout -modulus -in some.domain.csr`
which gives:
`Can't open Z:/extlib/_2020Q3__/ssl/openssl.cnf for reading, No such file or directory`
`19168:error:02001003:system library:fopen:No such process:crypto/bio/bss_file.c:69:fopen('Z:/extlib/_2020Q3__/ssl/openssl.cnf','r')`
`19168:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:`

I have not a `Z:` drive in my system so I suspect it is a leftover of the port build.

As remediation I had a simple `openssl.cnf` from a friend of mine: attached [here](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/files/10730246/openssl.cnf.txt) I put it in the main directory of my Perls `c:\straberry_all\openssl.cnf` and then I set the env var `OPENSSL_CONF=c:\straberry_all\openssl.cnf` and the parsing of the same CSR worked as expected.

Thanks

**Comment by LorenzoTa** [comment]
see also [the bug](https://rt.cpan.org/Public/Bug/Display.html?id=94143) reported IN 2014

**Comment by shawnlaffan** [comment]
Thanks for that link.  

So the solution/workaround seems to be that calling code needs to set OPENSSL_CONF to point to their own config file.  

This is documented under the "Environment" heading at https://www.openssl.org/docs/man1.1.1/man5/config.html

I'll leave this open as it should probably be noted as a known issue with the releases.

**Comment by shawnlaffan** [comment]
Info has been added to the known issues for 5.36 and 5.38, so closing this issue.
