### ISSUE TITLE
makefile.mk is no longer used to build perl

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/Perl-Dist-Strawberry#54]
Running a test build of 5.36 I hit an error when it tried to build perl where it cannot find ```makefile.mk```.

```
    * extracting 'C:\strawberry_build\download\perl-5.36.0.tar.gz'
##2023/01/25-15:56:41## BUILD FAILURE: read_file 'C:\strawberry_build\build\perl_core\perl-5.36.0\win32\makefile.mk' - o
pen: No such file or directory at ..\blib\lib/Perl/Dist/Strawberry/Step/InstallPerlCore.pm line 56.
    started: zip_dir('C:\strawberry_build\debug', 'C:\strawberry_build\output\1677301001_debug_dir.zip', 1)
```

Looks like it was removed in the 5.33 dev cycle as it is in 5.32 but not 5.34.  

In any case we need to find an alternate means of getting the version string at this line:
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/7a0356c27f69242b77d96603679ecc49dee09e7e/lib/Perl/Dist/Strawberry/Step/InstallPerlCore.pm#L56

**Comment by shawnlaffan** [comment]
This gets it to work and retains the old behaviour in case it is needed (includes a few context lines)

```perl
  #get verion string - e.g. '5.15.9'
  my $file_to_check = catfile($unpack_to, $perlsrc, qw/win32 makefile.mk/);
  if (!-e $file_to_check) {
    $file_to_check = catfile($unpack_to, $perlsrc, qw/win32 GNUMakefile/);
  }
  my ($version) = grep { /INST_VER/ } read_file($file_to_check);
  $version =~ s/^.*?(5\..*?)[\r\n]*$/$1/;
```

**Comment by genio** [comment]
https://github.com/genio/Perl-Dist-Strawberry/commit/8cc8a96c27f998ad963d2ee85d2e91264c93d145

**Comment by genio** [comment]
The comment on that basically did what you're doing except with Makefile vs GNUMakefile. I don't think it will matter for us

**Comment by shawnlaffan** [comment]
Either file work work.  It just has to exist.
