### ISSUE TITLE
We need to distribute a newer version of patch

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/Perl-Dist-Strawberry#74]
The version of patch currently used in the build system is long in the tooth and does not work with all diff and patch files.  

https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/c74cfe0addcdf6c798234c511efcbf779551d17b/share/64bit-5.36.0.1.pp#L26

At the moment I am copying the mingw64 patch into the path to get the builds to work, but we could also generate one using the extlibs build system.

**Comment by shawnlaffan** [comment]
See also https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/56#issuecomment-1451352018

**Comment by genio** [comment]
I think we can get rid of all of https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/c74cfe0addcdf6c798234c511efcbf779551d17b/share/64bit-5.36.0.1.pp#L23-L26 as they are no longer needed in the case of `dmake` and the rest come with the winlibs distribution we're using. I'll check on my Windows box when I get off work today as I could be misremembering

**Comment by shawnlaffan** [comment]
Makes sense to me. 

At the moment my builds start with a strawberry perl 5.32 at the front of the path.  I should probably put its dirs at the end of the path instead so the patch is collected from the winlibs dir.

**Comment by shawnlaffan** [comment]
Updated in 09364d6492e159cd77fcc19d70203c60bcac3a23

**Comment by shawnlaffan** [comment]
Although winlibs gcc 10.3 seems not to contain patch.exe.

**Comment by shawnlaffan** [comment]
This is in the latest dev release.
