### ISSUE TITLE
perl 5.36 cpan | Pod::Parser fails tests

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/Perl-Dist-Strawberry#75]
Pod::Parser has started failing tests when the patch from https://github.com/Perl/perl5/pull/20008 is applied to the perl source tree before building.  

This has already been reported with a fix in https://rt.cpan.org/Public/Bug/Display.html?id=145128

If need be we can build using our own patched source tree, as is already done for several other distributions.

**Comment by shawnlaffan** [comment]
Although I now see that Pod::Parser is discouraged in favour of Pod::Simple.
https://metacpan.org/pod/Pod::Parser#DESCRIPTION

In the build system it is required by Pod::Latex, and possibly others.  

Do we need to provide either of these distributions under the vendor dir?

**Comment by shawnlaffan** [comment]
@genio - Are you aware of a pressing need to distribute Pod::Latex?  If not then we can leave it commented out an close this issue.

**Comment by genio** [comment]
I see no issue with leaving this out.

**Comment by shawnlaffan** [comment]
Thanks @genio.  Closing issue.

**Comment by shawnlaffan** [comment]
We now have a patched version (#92) but I think we can still skip Pod::Latex.
