### ISSUE TITLE
sp536_20230311 unconditionally sets _WIN32_WINNT to 0x0a00

### ISSUE THREAD

**Issue by sisyphus** [StrawberryPerl/Perl-Dist-Strawberry#77]
I installed sp536_20230311 on my Windows 7 machine and _WIN32_WINNT and WINVER are set to 0xa00.
That's according to both perl (as reported by an Inline::C script) and a C program built using the C toolchain that ships with sp536_20230311.

The thing is that XS code might assume that, because _WIN32_WINNT is set to 0x0a00, the Windows operating system is at least Windows 10.
Is it unreasonable to make that assumption ?
I've recently seen one module (I forget which one it was) that did precisely that - and then, if _WIN32_WINNT was at 0x0a00, it called a Windows system function that didn't exist if the OS was pre-Windows 10.

I'm wondering if <code>ccflags</code> should specify _WIN32_WINNT to be the lesser of the value specified by the compiler and the value that is appropriate for the particular system on which Strawberry is being installed (ie 0x0601 for Windows 7, 0x0602 for Windows 8, 0x0a00 for Windows 10).
But my understanding of this might not be great, and it's probably something that's not going to bite often, so let me know if I should just close this.

This hasn't been an issue in the past because the compilers that shipped with Strawberry Perl all set _WIN32_WINNT to a conservatively low value.
For example, with Strawberry 5.32.x, _WIN32_WINNT was set to 0x0502 - which is just above Windows XP.

Cheers,
Rob

**Comment by genio** [comment]
As far as I can remember, this has always been an issue with Strawberry. It always reports with the version of Windows it was built on.

**Comment by sisyphus** [comment]
>  It always reports with the version of Windows it was built on.

For my own builds, perl always sees the _WIN32_WINNT value specified by the gcc toolchain's headers, irrespective of the Windows OS on which it has been built - but I don't know about Strawberry Perl.

The thing is that it's pretty easy to overwrite if you want to.
You just have to insert something like <code>-D_WIN32_WINNT=0x0602</code> into the <code>ccflags</code> entries in lib/Config_heavy.pl and lib/Config.pm, and it's all done.
I imagine that Strawberry's installation process could handle this task, having first established the actual version of Windows on which it is being installed.

Maybe it's more trouble than it's worth ... and it does also lead to the occasional "_WIN32_WINNT redefined" warning :-(

Cheers,
Rob

**Comment by shawnlaffan** [comment]
The simple view is to target the minimum supported version of windows, which at this stage is 8.1.  If it's a simple change to support older versions with little to no impact in more recent versions then I see no reason not to.  

If this setting is something that is normally done in the config.gc or config_H.gc files then it's now pretty easy to do.  We can also pass other build options.

**Comment by sisyphus** [comment]
> If this setting is something that is normally done in the config.gc or config_H.gc files then it's now pretty easy to do.

I'm fairly sure it cannot be set that way.
AFAIK, perl itself doesn't specify a value for _WIN32_WINNT.
When an XS module is being built, the value is taken from the compiler's header files.
In the toolchain that ships with SP-5.32.1 there's a number of header files (including _mingw.h, winresrc.h, sdkddkver.h and winsdkver.h) that do:
```
#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0x502
#endif
```
and I believe that's the sole reason that SP-5.32.1 XS compilations are conducted with a _WIN32_WINNT value of 0x502.
Of course, the 5.32.1 toolchain was built by the "Strawberry Perl Project" but I don't know whether @kmx has configured that build to apply 0x502 as the default value, or whether that's just the default that the mingw-w64 source provided at the time.

AIUI, it is intended that the default value can be avoided by defining _WIN32_WINNT to whatever you want prior to the processing of any header files - eg by specifying it in ccflags.
In my own Windows 7 builds, I make use of the GNUmakefile's BUILDOPTEXTRA option to insert <code>-D_WIN32_WINNT=0x601</code> into ccflags.
Of course, that has to be done before building perl. 
Otherwise, one can insert a _WIN32_WINNT value (post-build) into ccflags by hacking Config.pm and Config_heavy.pl.

In sp536_20230311, _mingw.h has:
```
#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0xa00
#endif
```

Anyway, there are perhaps more pressing matters to be dealt with first.

Cheers,
Rob

**Comment by shawnlaffan** [comment]
Thanks Rob.  

We're using the GCC 10.3 toolchain from winlibs so it will be whatever was used for that build system.  

It's something we can look at once we get a fully working 5.36 build.

**Comment by xenu** [comment]
>The thing is that XS code might assume that, because _WIN32_WINNT is set to 0x0a00, the Windows operating system is at least Windows 10.
Is it unreasonable to make that assumption ?

Code that does this is broken, it's not the right way to check the Windows version. If anything, XS modules should be setting _WIN32_WINNT to a desired value.

Also, it isn't just MinGW. The current versions of Windows SDK also default to 0x0a00 despite still supporting Windows 7.

**Comment by sisyphus** [comment]
> Code that does this is broken, it's not the right way to check the Windows version. 

Thanks, @xenu.
I take it that means that SP need to take no action on this, and that I should therefore close this ticket - which is what I shall do.

I'm quite happy for it to be re-opened if I've missed something.

Cheers,
Rob
