### ISSUE TITLE
https://strawberryperl.com/support.html still links to rt.cpan.org, which doesn't seem to want to be linked to 

### ISSUE THREAD

**Issue by guest20** [StrawberryPerl/Perl-Dist-Strawberry#91]
# What I saw:

Quoth https://strawberryperl.com/support.html

> Bug Reports
>
> please file a bug report (with as much details as possible) on our [Request Tracker](https://rt.cpan.org/Public/Dist/Display.html?Name=Perl-Dist-Strawberry)

but when you click the RT link, it says: 

<img width="496" alt="Screen Shot 2023-04-13 at 12 31 41" alt="Preferred bug tracker
Please visit the preferred bug tracker to report your issue." src="https://user-images.githubusercontent.com/3603869/231732736-7cf6adfd-e0e5-4493-8223-d6aa88a96757.png">

... which links here. 

# What I expected:

The "Bug Reports" section to link to the bug reporting site.

# Steps to reproduce

1. https://strawberryperl.com/support.html
2. scroll down a bit
3. click `Request Tracker`

# Suggested fix

1. update the link on the website, or  
2. jam a bug reporting form directly into the page, or 
4. ask rt.cpan.org to redirect instead of showing a list of tickets it knows nobody is looking at

**Comment by pryrt** [comment]
see also my July 2021 issue: https://github.com/StrawberryPerl/strawberryperl.com/issues/27

**Comment by guest20** [comment]
@pryrt Your crop is much more aggressive, do they bill by the pixel in Oregon?

**Comment by shawnlaffan** [comment]
PRs welcome.
