### ISSUE TITLE
Update release notes for 5.36 and 5.38

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/Perl-Dist-Strawberry#94]
- [x] List the patches we are applying from the 5.37 series.  Edit - only needed for 5.36. DOne in https://github.com/StrawberryPerl/strawberryperl.com/commit/0370e71f390ed6c8ddeedefe3733c4fd00fc3348
- [x] Note which modules are missing from previous releases? Edit - No.  The list of available modules is listed.  Missing modules could not be built and people can provide patches if they are needed.
- [x] Note which modules we are patching?  ([File::Find::Rule](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/88), [Pod::Parser](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/92), [Socket6](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/72))  Edit - no need as there are actually quite a few patched modules in the build system.  
- [x] ~Make sure we reference the correct Oracle Instant Client version.  ([spbuild PR 14](https://github.com/StrawberryPerl/spbuild/pull/14)) . See also release the notes template: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/4331b337df138ce06f064c6992b6d48ad5ef10cd/share/extra-files/release_notes.html.tt#L64~ Edit - we did not distribute this.
- [x] List the need for users to set OPENSSL_CONF when using openssl.exe.  #51

**Comment by aero** [comment]
Hello,

Do you plan to include 32bit version when releasing Strawberry Perl 5.36? 
like previous versions of Strawberry Perl used to do it before.
Some legacy Windows OLE/COM 32bit based components still rely on 32bit perl.

**Comment by shawnlaffan** [comment]
@aero - it's a fair question but is off topic for this issue.  Can you open a new issue instead?

**Comment by PhilterPaper** [comment]
Where do 5.36 and 5.38 (.msi packages) try to install? With 5.32 and before, it would install into \Strawberry, which I could rename to \Strawberry-5.xx and generate a soft link ("junction") from \Strawberry. This way, I could have multiple Strawberry Perls and switch between them at will (using \Strawberry in my PATH, etc.). I just tried 5.38 (and then 5.36), after `rmdir \Strawberry`, and all I get is an error popup: "Already installed version of Strawberry Perl (64-bit), cannot be upgraded; it has to be uninstalled first." What needs to be uninstalled, and how? Is there some configuration data hiding somewhere? I'm certainly not going to uninstall \Strawberry-5.32, 26, and 24 -- it is critical to have multiple versions available for testing.

**Comment by shawnlaffan** [comment]
This is a valid question but is somewhat off topic for this issue.  Can you open a new issue, or perhaps a discussion thread would be good for this?  https://github.com/StrawberryPerl/Perl-Dist-Strawberry/discussions

As a quick response, that part of the build system is unchanged from the 5.32 builds, for which the default is C:\strawberry.  Unless something on the build machine has been baked-in?  Or perhaps some registry setting is now triggering at install time?

**Comment by shawnlaffan** [comment]
All tasks for this issue are completed or not needed.  Closing.
